### ISSUE TITLE
__slots__ without __getstate__

### ISSUE THREAD

**Issue by dschien** [hgrecco/pint#1036]
Hi, I'm trying to pickle a df with hdf5. 

That fails with the below error because `__getstate__` has vanished from class `UnitsContainer`

```python
  File "/Users/csxds/workspaces/venvs/dimpact_test/lib/python3.7/site-packages/tables/attributeset.py", line 494, in __setattr__
    self._g__setattr(name, value)
  File "/Users/csxds/workspaces/venvs/dimpact_test/lib/python3.7/site-packages/tables/attributeset.py", line 436, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 708, in tables.hdf5extension.AttributeSet._g_setattr
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copyreg.py", line 73, in _reduce_ex
    "defining __getstate__ cannot be pickled") from None
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```
Any chance this can be brought back?

Many thanks

**Comment by crusaderky** [comment]
What is a df? Could you post an example where you create an object that fails to pickle/unpickle? I'm asking because there are already pickle/unpickle tests and I find weird that they don't detect anything.

**Comment by dschien** [comment]
df = pandas DataFrame. I'll try to extract a minimal example. Cheers

**Comment by dschien** [comment]
Here is the example: https://github.com/dschien/pint-pandas-pickle

Simply install deps as usual.

Then run main.py.

Result

```python
(pint-pandas-6) ➜  pickle-pint-pandas python main.py
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    run()
  File "main.py", line 17, in run
    store.get_storer('model_data').attrs.metadata = metadata
  File "/Users/csxds/workspaces/venvs/pint-pandas-6/lib/python3.7/site-packages/tables/attributeset.py", line 483, in __setattr__
    self._g__setattr(name, value)
  File "/Users/csxds/workspaces/venvs/pint-pandas-6/lib/python3.7/site-packages/tables/attributeset.py", line 425, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 713, in tables.hdf5extension.AttributeSet._g_setattr
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copyreg.py", line 73, in _reduce_ex
    "defining __getstate__ cannot be pickled") from None
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
Closing remaining open files:test.hdf5...done
```

**Comment by crusaderky** [comment]
Replicated.
This is triggered by https://github.com/PyTables/PyTables/blob/f54d8d93e126c539ee4231d7fb05980be792052a/tables/hdf5extension.pyx#L713

I honestly had no idea that anybody was still using pickle protocol 0...
Working on a fix

**Comment by dschien** [comment]
> Replicated.
> This is triggered by https://github.com/PyTables/PyTables/blob/f54d8d93e126c539ee4231d7fb05980be792052a/tables/hdf5extension.pyx#L713
> 
> I honestly had no idea that anybody was still using pickle protocol 0...
> Working on a fix

Super. Thanks a lot!
