### ISSUE TITLE
Unit reduction on Quantity results in KeyError

### ISSUE THREAD

**Issue by matthiaskoenig** [hgrecco/pint#1058]
Trying to do some simple unit manipulation with pint 0.11, but getting the following issue
```
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity
dose = Q_(10.0, "mg/kg") * Q_(1.0, "mole/g")
print(dose)
dose.ito_reduced_units()
```
results in
```
Traceback (most recent call last):
  File "/home/mkoenig/git/pkdb_analysis/pkdb_analysis/deprecated/oven.py", line 7, in <module>
    dose.ito_reduced_units()
  File "/home/mkoenig/envs/pkdb_analysis/lib/python3.7/site-packages/pint/quantity.py", line 625, in ito_reduced_units
    newunits = newunits.add(unit2, exp / power).remove([unit1])
  File "/home/mkoenig/envs/pkdb_analysis/lib/python3.7/site-packages/pint/util.py", line 362, in remove
    new._d.pop(k)
KeyError: 'kilogram'
```

**Comment by matthiaskoenig** [comment]
As a workaround
```
dose.ito_base_units().ito_reduced_units()
```
works, but in the reduction this should happen automatically, otherwise one always has to call `to_base_units` before reducing units to be save.

**Comment by Amaretto-Coke** [comment]
So the intended solution is every time `.to_reduced_units()` is called, it internally converts to base units first?

**Comment by matthiaskoenig** [comment]
I am no expert with pint, so I am not sure what is the best solution here. For me it seemed just very strange that such a simple Quantity cannot be reduced. 
It should be no problem for the `to_reduced_units()` to deal with Quantities which have multiple variants of a base unit in it.

**Comment by crusaderky** [comment]
Reproduced with git master tip.
```python
import pint
q = pint.Quantity(1, "milligram / gram / kilogram")
q.to_reduced_units()
```
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-eb062ab23d54> in <module>
----> 1 q.to_reduced_units()

pint/quantity.py in to_reduced_units(self)
    668         # can we make this more efficient?
    669         newq = copy.copy(self)
--> 670         newq.ito_reduced_units()
    671         return newq
    672 

pint/quantity.py in ito_reduced_units(self)
    655                     power = self._REGISTRY._get_dimensionality_ratio(unit1, unit2)
    656                     if power:
--> 657                         newunits = newunits.add(unit2, exp / power).remove([unit1])
    658                         break
    659 

pint/util.py in remove(self, keys)
    373         new = self.copy()
    374         for k in keys:
--> 375             new._d.pop(k)
    376         new._hash = None
    377         return new

KeyError: 'gram'
```
As mentioned by OP, ``.to_base_units()`` is unaffected.
