### ISSUE TITLE
ValueError: Boolean value of Quantity with offset unit is ambiguous.

### ISSUE THREAD

**Issue by afrazahmad21** [hgrecco/pint#1169]
# Temperature
    T = 35 * u.degC

    print(type(T))
    # Pressure (from operation data)
    P = 101.325 * u.kPa  # 1 atp

    print(P)
    # Duty flow rate
    Q = 0.007165 * u.m ** 3 / u.sec  # equivalent to 429.91 L/min

    # Fluid property (from operation data)
    fluid = Stream('water', T=T, P=P, Q=Q)

Pint version = 0.15

Error StackTrace

Traceback (most recent call last):
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/Modules/CalculationSheet/sanjel/DashboardTable/PumpEfficiency.py", line 204, in <module>
    fluid = Stream('water', T=T, P=P, Q=Q)
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/venv/lib/python3.7/site-packages/thermo/stream.py", line 215, in __init__
    T=T, P=P, Vf_TP=V_TP)
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/venv/lib/python3.7/site-packages/thermo/mixture.py", line 451, in __init__
    self.Chemicals = [Chemical(component, P=P, T=T) for component in self.components]
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/venv/lib/python3.7/site-packages/thermo/mixture.py", line 451, in <listcomp>
    self.Chemicals = [Chemical(component, P=P, T=T) for component in self.components]
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/venv/lib/python3.7/site-packages/thermo/chemical.py", line 578, in __init__
    self.calculate(T, P)
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/venv/lib/python3.7/site-packages/thermo/chemical.py", line 587, in calculate
    if T:
  File "/home/afraz/Desktop/IPMS-PYTHON/IPMS-API/venv/lib/python3.7/site-packages/pint/quantity.py", line 1556, in __bool__
    raise ValueError("Boolean value of Quantity with offset unit is ambiguous.")
ValueError: Boolean value of Quantity with offset unit is ambiguous.

**Comment by dopplershift** [comment]
I'm not sure this is a bug. The problem is, with an offset unit, it's not clear what the right answer is. Let's take the example of 0 degrees Celsius. Being zero, this could reasonably be considered False. If you convert to Kelvin, this is now 273.15 and would be True.

**Comment by jthielen** [comment]
See also: https://github.com/hgrecco/pint/issues/866 and https://github.com/hgrecco/pint/pull/965
