### ISSUE TITLE
pickle Quantity

### ISSUE THREAD

**Issue by impact27** [hgrecco/pint#1175]
If I pickle a Quantity:
```python
import pint
import pickle
foo = pint.get_application_registry().Quantity(1, 's')
with open("file.pkl", 'bw') as f:
    pickle.dump(foo, f)
```
And the unpickle it (using the `application_registry` so it should work with pickle):
```python
import pint
import pickle
bar = pint.get_application_registry().Quantity(0.5, 's')
with open("file.pkl", 'br') as f:
    foo = pickle.load(f)

foo > bar
```
I get the following error.
```python
Traceback (most recent call last):

  File "C:\Users\Quentin.Peter\Desktop\untitled0.py", line 16, in <module>
    foo > bar

  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\pint\quantity.py", line 1511, in <lambda>
    __lt__ = lambda self, other: self.compare(other, op=operator.lt)

  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\pint\quantity.py", line 102, in wrapped
    result = f(self, *args, **kwargs)

  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\pint\quantity.py", line 1501, in compare
    raise ValueError("Cannot compare Quantity and {}".format(type(other)))

ValueError: Cannot compare Quantity and <class 'pint.quantity.Quantity'>
```
I can fix it by adding in `__init__.py::_unpickle`
```python
if cls.__name__ == "Quantity":
        cls = _APP_REGISTRY.Quantity
```

**Comment by hgrecco** [comment]
This should be fixed in 0.16.1 Thanks for reporting
