### ISSUE TITLE
ValueError on comparison with unparsable string

### ISSUE THREAD

**Issue by rfrowe** [hgrecco/pint#1178]
# Reproduction:
```python
>>> import pint
>>> reg = pint.UnitRegistry()
>>> reg.mph == '*'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pint/unit.py", line 243, in __eq__
    return self._units == other
  File "/usr/local/lib/python3.8/site-packages/pint/util.py", line 434, in __eq__
    other = ParserHelper.from_string(other, self._non_int_type)
  File "/usr/local/lib/python3.8/site-packages/pint/util.py", line 610, in from_string
    ret = build_eval_tree(gen).evaluate(
  File "/usr/local/lib/python3.8/site-packages/pint/pint_eval.py", line 98, in evaluate
    raise DefinitionSyntaxError('missing unary operator "%s"' % op_text)
pint.errors.DefinitionSyntaxError: missing unary operator "*"
```

# Expected Behavior
```python
>>> reg.mph == '*'
False
```

# Solution
In `UnitsContainer.__eq__`, if `other` is a `str` we attempt to parse `other` into a unit indiscriminately. This should be wrapped in a try-except block.

**Comment by hgrecco** [comment]
Sounds good to me. Please submit a PR
