### ISSUE TITLE
Property setter is ignored in wrapped custom class

### ISSUE THREAD

**Issue by pasbec** [hgrecco/pint#1207]
Dear pint developers,

Firstly thanks for a pint!

During some tests with pint I realized that property setters of a wrapped class are ignored. Is this by design or maybe a bug?

See below for a simple example:
```python
from pint import UnitRegistry

ureg = UnitRegistry()
Quantity = ureg.Quantity

class A:
    _a = None
    
    def __init__(self, a):
        print("Init a to {}".format(a))
        self._a = a
        
    def __getitem__(self, key):
        print("Get a as item with value {}".format(self._a))
        return self._a
    
    def __setitem__(self, key, value):
        print("Set a as item to value {}".format(value))
        self._a = value
        
    def __repr__(self):
        return str(self._a)
    
    @property
    def a(self):
        print("Get (raw) a as property with value {}".format(self._a))
        return self[0]
    
    @a.setter
    def a(self, value):
        print("Set (raw) a as property to value {}".format(value))
        self[0] = value
    
test = Quantity(A(0), "m")

print("Test item setter:")
test[0] = 3 * ureg.m
print(test[0])
print(test.a)

print("Test property setter:")
test.a = 10
print(test.a)
print(test[0])
```
```txt
Init a to 0
Test item setter:
Set a as item to value 3
Get a as item with value 3
3 meter
Get (raw) a as property with value 3
Get a as item with value 3
3
Test property setter:
10
Get a as item with value 3
3 meter
```

In the example you can see that the property setter never gets called at all.
This could be fixed by deriving from Quantity with a custom `__setattr__` method but this sadly breaks lot of other things.

Any ideas?

Thanks in advance

**Comment by pasbec** [comment]
What I tried to fix it is the following:
```python
import pint
from pint import UnitRegistry

ureg = UnitRegistry()

class Quantity(pint.quantity.Quantity):

    _REGISTRY = ureg

    def __getattr__(self, key):
        if key != "_magnitude" \
           and hasattr(self, "_magnitude") \
           and hasattr(self._magnitude, "keys") \
           and callable(self._magnitude.keys) \
           and key in self._magnitude.keys():
            return self[key]
        else:
            return super().__getattr__(key)

    def __setattr__(self, key, value):
        if key != "_magnitude" \
           and hasattr(self, "_magnitude") \
           and hasattr(self._magnitude, "keys") \
           and callable(self._magnitude.keys) \
           and key in self._magnitude.keys():
            self[key] = value
        else:
            super().__setattr__(key, value)

class A:
    _a = None
    
    def __init__(self, a):
        print("Init a to {}".format(a))
        self._a = a
        
    def __getitem__(self, key):
        print("Get a as item with value {}".format(self._a))
        return self._a
    
    def __setitem__(self, key, value):
        print("Set a as item to value {}".format(value))
        self._a = value
        
    def __repr__(self):
        return str(self._a)
    
    @property
    def a(self):
        print("Get (raw) a as property with value {}".format(self._a))
        return self[0]
    
    @a.setter
    def a(self, value):
        print("Set (raw) a as property to value {}".format(value))
        self[0] = value
    
test = Quantity(A(0), "m")

print("Test item setter:")
test[0] = 3 * ureg.m
print(test[0])
print(test.a)

print("Test property setter:")
test.a = 10
print(test.a)
print(test[0])
```
```
Init a to 0
Test item setter:
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    test[0] = 3 * ureg.m
  File "C:\Users\test\Apps\Anaconda3\lib\site-packages\pint\quantity.py", line 1864, in __setitem__
    extra_msg=". Assign a quantity with the same dimensionality "
pint.errors.DimensionalityError: Cannot convert from '3 meter' to 'meter'. Assign a quantity with the same dimensionality or access the magnitude directly as `obj.magnitude[0] = 3 meter`.
```
Which is quite strange - but I'm probably not supposed to create my own Quantity class that fixes the above issue.

Any advice is very much appreciated!
