### ISSUE TITLE
import fails at cannot import name 'exp'

### ISSUE THREAD

**Issue by e3rd** [hgrecco/pint#1212]
Pint Version: 0.16.1
Numpy not installed

```bash
python3 -c "from pint import UnitRegistry; print(1)"
```
produces
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File
"/home/pspringer/.local/lib/python3.6/site-packages/pint/__init__.py",
line 16, in <module>
    from .context import Context
  File
"/home/pspringer/.local/lib/python3.6/site-packages/pint/context.py",
line 15, in <module>
    from .definitions import Definition, UnitDefinition
  File
"/home/pspringer/.local/lib/python3.6/site-packages/pint/definitions.py",
line 13, in <module>
    from .converters import LogarithmicConverter, OffsetConverter,
ScaleConverter
  File
"/home/pspringer/.local/lib/python3.6/site-packages/pint/converters.py",
line 12, in <module>
    from .compat import HAS_NUMPY, exp, log  # noqa: F401
ImportError: cannot import name 'exp'
```

**Comment by hgrecco** [comment]
Cannot reproduce:
```
$ python3 -c "from pint import UnitRegistry; print(1)"
1
$ python
Python 3.8.2 (default, Mar 26 2020, 10:43:30)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

**Comment by e3rd** [comment]
False positive, duplicitous installation. Affected colleague could not reproduce after re-installation neither. Sorry for bothering.
