### ISSUE TITLE
ZeroDivisionError converting from 0 inverse length to energy in 'spectroscopy' context

### ISSUE THREAD

**Issue by rebeccafair** [hgrecco/pint#1214]
In `pint 0.16.1` The following causes a `ZeroDivisionError`:
```
import pint

ureg = pint.UnitRegistry()
ureg.enable_contexts('spectroscopy')

x = 0*ureg('1/cm')
y = x.to('meV')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\quantity.py", line 661, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\quantity.py", line 610, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\registry.py", line 954, in convert
    return self._convert(value, src, dst, inplace)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\registry.py", line 1836, in _convert
    src = self._active_ctx.transform(a, b, self, src)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\context.py", line 349, in transform
    return self[(src, dst)].transform(src, dst, registry, value)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\context.py", line 251, in transform
    return self.funcs[_key](registry, value, **self.defaults)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\context.py", line 30, in func
    return ureg.parse_expression(eq, value=value, **kwargs)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\registry.py", line 1272, in parse_expression
    lambda x: self._eval_token(x, case_sensitive=case_sensitive, **values)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\pint_eval.py", line 93, in evaluate
    return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\quantity.py", line 1287, in __rtruediv__
    return self.__class__(other_magnitude / self._magnitude, 1 / self._units)
ZeroDivisionError: float division by zero
```
When doing the conversion in one line `x = 0*ureg('1/cm').to('meV')` this error is not raised.

**Comment by jules-ch** [comment]
In your second example, [python operator precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence) makes evaluation of `ureg('1/cm').to('meV')` first to  ~ `0.123984 meV` and you then multiply by 0 which evaluate to `0 meV`.

If you try `x = (0*ureg('1/cm')).to('meV')` you will have the same result which raises `ZeroDivisionError`.

`[wavenumber] <-> [length]: 1 / value` this conversion definition in the context is responsible for this ZeroDivisionError.

**Comment by rebeccafair** [comment]
Thanks for the explanation, is this intended behaviour or just an oversight? Is there a workaround aside from just catching the error?

**Comment by jules-ch** [comment]
It is the inteded behaviour. Dividing by Zero raises ZeroDivisionError by default in Python.

For your use case, you can either catch the exception or you could use numpy float64 datatype if you're using numpy. 
Dividing by zero in is returning np.inf, which will return `0 meV`. It will output a `RuntimeWarning` that you can filter if you want.

Numpy float datatype is following standards https://en.wikipedia.org/wiki/IEEE_754, which outputs infinity for division by zero.
like so :

```python
from pint import UnitRegistry
import numpy as np

ureg = UnitRegistry()
ureg.enable_contexts('spectroscopy')

with numpy.errstate(divide='ignore'):
    x = (np.float64(0)*ureg('1/cm')).to('meV')
```

**Comment by rebeccafair** [comment]
We are using Numpy and are currently filtering the `RuntimeWarning`, so will continue with that route.

Thank you, just wanted to check that we weren't doing anything unexpected, so I'm happy to close this issue.
