### ISSUE TITLE
Unable to import pint after installing pint-pandas

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1268]
After using pint for a while, I installed pint-pandas with pip using:

```
pip install pint-pandas
```

I already have pandas installed (v 1.2.0) and pint (v 0.16.1). I tried to run through the example given in the [documentation](https://pint.readthedocs.io/en/0.16.1/pint-pandas.html).
However, when I try to import pint in my python interpreter (via ``import pint``) I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/pint/__init__.py", line 40, in <module>
    from pint_pandas import PintArray, PintType
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/pint_pandas/__init__.py", line 1, in <module>
    from .pint_array import PintArray, PintType
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/pint_pandas/pint_array.py", line 696, in <module>
    PintArray._add_arithmetic_ops()
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 1246, in _add_arithmetic_ops
    setattr(cls, "__add__", cls._create_arithmetic_method(operator.add))
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/pint_pandas/pint_array.py", line 622, in _create_arithmetic_method
    return cls._create_method(op)
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/pint_pandas/pint_array.py", line 617, in _create_method
    op_name = ops._get_op_name(op, True)
AttributeError: module 'pandas.core.ops' has no attribute '_get_op_name'
```
I tried updating pandas to the latest version (1.2.3 from 1.2.0) but the issue persists. Just from looking at the traceback, it looks like pint-pandas depends on some of the internal pandas API (``_get_opt_name``), which, since it's an internal method prepended by an underscore, is not guaranteed to be stable. This seems like a bad idea.

**Comment by jules-ch** [comment]
This was fixed in pint-pandas https://github.com/hgrecco/pint-pandas/pull/53

**Comment by hgrecco** [comment]
Please update to Pint 0.17 and Pint-Pandas 0.2
