### ISSUE TITLE
Handle array creation functions such as np.asanyarray

### ISSUE THREAD

**Issue by Illviljan** [hgrecco/pint#1406]
It's common for downstream packages to force inputs to numpy-likes using `np.asarray`, `np.asanyarray` etc. These have a `like` argument to handle duckarrays, it would be nice if pint handled these methods. Dask supports this if you want ideas how to implement it.

```python
import numpy as np 
import pint
import dask.array as da

a = np.array([1, 2, 3])
aa = pint.Quantity(a, "m")
np.asanyarray(a, like=aa)
Traceback (most recent call last):

  File "<ipython-input-7-59dc788bb8ad>", line 1, in <module>
    np.asanyarray(a, like=aa)

TypeError: no implementation found for 'numpy.asanyarray' on types that implement __array_function__: [<class 'pint.quantity.Quantity'>]

# dask handles this just fine:
np.asanyarray(a, like=da.array(a))
dask.array<array, shape=(3,), dtype=int32, chunksize=(3,), chunktype=numpy.ndarray>
```

**Comment by jthielen** [comment]
This is unfortunately not well-defined for Pint Quantities, as a single `like` argument isn't enough info to unambiguously specify the output (is it "like" in just the array type sense, or "like" also in units?), as alluded to previously in https://github.com/hgrecco/pint/issues/882. Also, if we want this `like` argument behavior to be consistent with `np.ones_like`, `np.zeros_like`, and `np.full_like` as they're currently implemented, then this would be a no-op (although, including a Pint-specific warning may be more useful than the current `TypeError`). That being said, if there is a desire to change the `np.*_like` behavior (https://github.com/hgrecco/pint/issues/882) and so also take advantage of these NEP-35 additions, then that could definitely be considered!

**Comment by Illviljan** [comment]
I think it should be array type and units. You'd lose the point of pint if the units were forgotten:

```python
import numpy as np
import pint
import dask.array as da


def torque(r, F, like_r=None, like_F=None):
    """Low level implementation."""
    r = np.asanyarray(r, like=like_r) if like_r is not None else np.asanyarray(r)
    F = np.asanyarray(F, like=like_F) if like_F is not None else np.asanyarray(F)

    return r * F


def torque_pint(r, F):
    """High level wrapper adding units"""
    like_r = pint.Quantity([], "m")
    like_F = pint.Quantity([], "N")
    return torque(r, F, like_r=like_r, like_F=like_F)  # [Nm]


def torque_dask(r, F):
    """High level wrapper adding dask"""
    like_r = da.array([])
    like_F = da.array([])
    return torque(r, F, like_r=like_r, like_F=like_F)


torque_pint(2, 3)
Traceback (most recent call last):

  File "<ipython-input-44-2b30fd66181f>", line 1, in <module>
    torque_pint(2, 3)

  File "<ipython-input-42-815053e56d26>", line 18, in torque_pint
    return torque(r, F, like_r=like_r, like_F=like_F)  # [Nm]

  File "<ipython-input-42-815053e56d26>", line 8, in torque
    r = np.asanyarray(r, like=like_r) if like_r is not None else np.asanyarray(r)

TypeError: no implementation found for 'numpy.asanyarray' on types that implement __array_function__: [<class 'pint.quantity.Quantity'>]


torque_dask(2, 3)
Out[45]: dask.array<mul, shape=(), dtype=int32, chunksize=(), chunktype=numpy.ndarray>
```
