### ISSUE TITLE
KeyError with custom derived quantity

### ISSUE THREAD

**Issue by rufuswilson** [hgrecco/pint#1418]
I have defined a new derived dimension with
```
[molar_energy] = [energy] / [substance]
```

However, if I do the following it complains:
```
>>> UR.get_compatible_units('[molar_energy]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cedric/.local/share/virtualenvs/MatDB--uGOYMXa/lib/python3.9/site-packages/pint/registry.py", line 881, in get_compatible_units
    equiv = self._get_compatible_units(input_units, group_or_system)
  File "/Users/cedric/.local/share/virtualenvs/MatDB--uGOYMXa/lib/python3.9/site-packages/pint/registry.py", line 2082, in _get_compatible_units
    ret = super()._get_compatible_units(input_units, group_or_system)
  File "/Users/cedric/.local/share/virtualenvs/MatDB--uGOYMXa/lib/python3.9/site-packages/pint/registry.py", line 1835, in _get_compatible_units
    ret = super()._get_compatible_units(input_units, group_or_system)
  File "/Users/cedric/.local/share/virtualenvs/MatDB--uGOYMXa/lib/python3.9/site-packages/pint/registry.py", line 891, in _get_compatible_units
    return self._cache.dimensional_equivalents[src_dim]
KeyError: <UnitsContainer({'[length]': 2, '[mass]': 1, '[substance]': -1, '[time]': -2})
```

I saw that there is a conversion included in a context but I don't use it. What I am doing wrong?

**Comment by rufuswilson** [comment]
OK. So I just added a new unit and it fixed the problem.

```
# Molar Energy
[molar_energy] = [energy] / [substance]
mol_en = J / mol
```
