### ISSUE TITLE
Specifying the floating precision of unit powers

### ISSUE THREAD

**Issue by iiwolf** [hgrecco/pint#1487]
Hello,

I am working with convection coefficients and they have some funky floating powers. Is there a way to specify precision of the units when reducing the units? For example I have the following equation

```python
h_c = 0.023 * V ** 0.8 * k ** 0.6 * (rho * cp) ** 0.4 / (D ** 0.2 * nu ** 0.4)
```

That I can properly reduced to base units

```python
h_c.to_base_units()
<Quantity(15710.5834, 'kilogram / kelvin ** 0.6 / meter ** 5.55112e-17 / second ** 2.6')>
````

But notice the `meter ** 5.55112e-17`. So that if I try to reduce to the units I want ("W/(m ** 2 * K)") or just `to_reduced_units()` I get the following error.

```python
(0.023 * (V ** 0.8 * k ** 0.6 * (rho * cp) ** 0.4) / (D ** 0.2 * nu ** 0.4)).to_reduced_units()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/quantity.py", line 738, in to_reduced_units
    newq.ito_reduced_units()
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/quantity.py", line 728, in ito_reduced_units
    return self.ito(newunits)
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/quantity.py", line 637, in ito
    self._magnitude = self._convert_magnitude(other, *contexts, **ctx_kwargs)
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/quantity.py", line 616, in _convert_magnitude
    return self._REGISTRY.convert(
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/registry.py", line 947, in convert
    return self._convert(value, src, dst, inplace)
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/registry.py", line 1830, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/registry.py", line 1433, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/home/ijw/.local/lib/python3.8/site-packages/pint/registry.py", line 980, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'kilogram ** 0.4 * watt ** 0.6 / centimeter ** 0.2 / kelvin ** 0.6 / meter / second ** 0.8' ([mass] / [length] ** 5.55112e-17 / [temperature] ** 0.6 / [time] ** 2.6) to 'kilogram ** 0.4 * watt ** 0.6 / centimeter ** 1.2 / kelvin ** 0.6 / second ** 0.8' ([mass] / [temperature] ** 0.6 / [time] ** 2.6)
```
Ultimately I think I just want to be able to truncate the powers of the units to 16 or so to be able to reduce. I tried a few different things and searched around, but could come up with anything clean.

Thanks so much! Love the library and I use it extensively.

**Comment by jules-ch** [comment]
I'd advise you to use Fraction for unit ratio. Thus unit powers should be reduced accordingly.

Can you update your minimal example with definition for V rho cp D & nu.
I can guess rho & cp but not the other, just for the sake of reproductibility.

About Fraction, I think we need to push this to use Fraction everywhere for unit powers or at least for float ratio.

**Comment by andrewgsavage** [comment]
> at least for float ratio.

As soon as the user uses a float, the fractional conversion cannot be exact, so the input is inexact.
Therefore the fractional logic will give an inexact result, eg
```
Fraction(0.2)*5
Fraction(18014398509481985, 18014398509481984)
```

There is no way to get the above example `h_c = 0.023 * V ** 0.8 ...` correct in all calculations.

The user would have to use fraction for the `h_c = 0.023 * V ** Fraction("0.8") ...` which is cumbersome so I doubt many would do so

We could make `Quantity.__pow__(string)` convert the string to an int or fraction, which would allow `h_c = 0.023 * V ** "0.8" ...` but that feels just as odd.


AI gave this PR https://github.com/hgrecco/pint/pull/2377 which changes behaviour for float only using `math.isclose(value, 0.0, abs_tol=1e-10)`, which feels like a good way to fix this
