### ISSUE TITLE
Error: 'degree_Celsius' is not defined in the unit registry

### ISSUE THREAD

**Issue by giannisdravilas** [hgrecco/pint#1502]
While executing the following function called by a python process and using MetPy, I sometimes get an UndefinedUnitError by pint.

```
def calc2(L2,i):
    for lon in range(len(lons)//7, 2*len(lons)//7):
        L = []
        for lat in range(len(lats)):
            L.append(mpcalc.parcel_profile(flipped_levels*units.hPa, t2m[lat][lon]*units.degC, dp2m[lat][lon]*units.degC).to('degC')) if grid_point_has_sea(lons[lon],lats[lat]) else L.append([0 for i in range(23)]*units.degC)
        L2.append(L)
```
The error is raised about once every 10 times the function is executed and I have only encountered it on Pint 0.19, as on version 0.18 the function is executed without any problem.

I am not sure whether this is a MetPy or Pint bug, but according to the documentation I think 'degree_Celsius' should be in the unit registry.

```
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "my_program.py", line 73, in calc2
    L2.append(L)
  File "<string>", line 2, in append
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 243, in serve_client
    request = recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/usr/local/lib/python3.8/dist-packages/pint/__init__.py", line 78, in _unpickle_quantity
    return _unpickle(application_registry.Quantity, *args)
  File "/usr/local/lib/python3.8/dist-packages/pint/__init__.py", line 71, in _unpickle
    application_registry.parse_units(name)
  File "/usr/local/lib/python3.8/dist-packages/pint/registry.py", line 1195, in parse_units
    units = self._parse_units(input_string, as_delta, case_sensitive)
  File "/usr/local/lib/python3.8/dist-packages/pint/registry.py", line 1432, in _parse_units
    return super()._parse_units(input_string, as_delta, case_sensitive)
  File "/usr/local/lib/python3.8/dist-packages/pint/registry.py", line 1228, in _parse_units
    cname = self.get_name(name, case_sensitive=case_sensitive)
  File "/usr/local/lib/python3.8/dist-packages/pint/registry.py", line 715, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'degree_Celsius' is not defined in the unit registry
---------------------------------------------------------------------------
```

**Comment by giannisdravilas** [comment]
I tried reproducing the problem in a small example, but with no luck.
I have now set the `application_registry` as you mentioned and will do some tests to see whether the problem persists or not.

**Comment by giannisdravilas** [comment]
The solution provided with setting up the `application_registry` has so far worked and the error has not appeared again, so I close the issue for now. Thanks.
