### ISSUE TITLE
Error importing with Python3.10

### ISSUE THREAD

**Issue by dilawar** [hgrecco/pint#1511]
I am on Arch Linux with Python3.10.2. I installed `pint` using pip `python3 -m pip install pint`. When I try to import it, I am getting the following error.

```
[dilawar@inspiron ~]$ python3
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dilawar/.local/lib/python3.10/site-packages/Pint-0.19.1-py3.10.egg/pint/__init__.py", line 30, in <module>
  File "/home/dilawar/.local/lib/python3.10/site-packages/Pint-0.19.1-py3.10.egg/pint/registry.py", line 69, in <module>
  File "/home/dilawar/.local/lib/python3.10/site-packages/Pint-0.19.1-py3.10.egg/pint/parser.py", line 21, in <module>
ModuleNotFoundError: No module named 'pint._vendor'
>>> 
```

**Comment by hgrecco** [comment]
That is strange, tests on Python 3.10 are passing. Which pip version are using?
