### ISSUE TITLE
Locale formatting does not load 

### ISSUE THREAD

**Issue by GillesJ** [hgrecco/pint#1523]
For localization of units I am testing pint + babel as per [tutorial example](https://pint.readthedocs.io/en/stable/tutorial.html#localizing). I suspect the babel-provided CLDR data is not properly parsed or passed to the pint formatter based off the stack-trace.

Example:
```
ureg = pint.UnitRegistry()
accel = 1.3 * ureg['meter/second**2']
print(str(accel.format_babel(locale='fr_FR')))

ureg = pint.UnitRegistry(fmt_locale='fr_FR')
accel = 1.3 * ureg['meter/second**2']
print(str(accel))
```
Expected output:
```
>> '1.3 mètre par seconde²'
>> '1.3 mètre par seconde²'
```
Stacktrace / error:
```
Traceback (most recent call last):
  File "/Users/gilles/repos/testpint/test.py", line 5, in <module>
    str(accel.format_babel(locale='fr_FR'))
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/quantity.py", line 483, in format_babel
    obj.units.format_babel(spec, **kwspec),
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/unit.py", line 124, in format_babel
    return units.format_babel(spec, registry=self._REGISTRY, **kwspec)
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/util.py", line 466, in format_babel
    return format_unit(self, spec, registry=registry, **kwspec)
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py", line 411, in format_unit
    return fmt(unit, registry=registry, **options)
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py", line 227, in format_default
    return formatter(
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py", line 366, in formatter
    neg_ret = _join(division_fmt, neg_terms)
  File "/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py", line 42, in _join
    if not __JOIN_REG_EXP.search(fmt):
TypeError: expected string or bytes-like object
```

**Comment by jules-ch** [comment]
We can put a warning in the docs for the time being

**Comment by jules-ch** [comment]
Closing this, bable version has been added to `setup.cfg`, try installing with `pip install pint[babel]`
