### ISSUE TITLE
Using "#" modifier in default_format raises error in format

### ISSUE THREAD

**Issue by caspar-iqm** [hgrecco/pint#1526]
With pint 0.19.2, using the "#" (`to_compact`) modifier in `default_format` is broken. Using the modifier explicitly works.

This is related to #1413, but it's actually a separate bug so I'll report it as a separate issue.

## To reproduce
```py
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> ureg.default_format = ".3f#P"
>>> q = ureg.Quantity('1e-6 meter')
>>> print(f'{q:.3f#P}')  # Using the # modifier explicitly works as expected
1.000 micrometer
>>> str(q)  # Using the default_format setting above breaks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\site-packages\pint\quantity.py", line 324, in __str__
    return format(self)
  File "...\site-packages\pint\quantity.py", line 436, in __format__
    mstr = format(obj.magnitude, mspec).replace("\n", "")
ValueError: Invalid format specifier
```

## Cause
Running the same example above in the debugger leads to the cause in `Quantity.__format__`:

![image](https://user-images.githubusercontent.com/69967181/169776991-d344fcc5-3e11-40da-9ae2-eddaad280893.png)

There are two issues visible here:
1. `split_format` returns "#" in `mspec`, but in this case it should have been in `uspec`
2. The "special handling" if clause tests for `if "#" in spec`, but we are using default formatting here so `spec == ""`.

I think an immediate fix for this error would be to change the if clause to `if "#" in mspec or "#" in uspec`.

## Workaround
Here is a monkey-patch workaround for 0.19.2, basically taking the default_format resolution outside of __format__:

```py
from pint import UnitRegistry
ureg = UnitRegistry()

_real_format = ureg.Quantity.__format__

def _wrapped_format(self, spec: str) -> str:
    if spec=='':
        return _real_format(self, self.default_format)
    else:
        return _real_format(self, spec)

ureg.Quantity.__format__ = _wrapped_format 
```

**Comment by andrewgsavage** [comment]
this is fixed now
