### ISSUE TITLE
Bug: mod `%` operator behaves inconsistently

### ISSUE THREAD

**Issue by segf4ult** [hgrecco/pint#1535]
```
# Correct answer
>>> -270 % 360
90
```
```
# Using meters, and no quantity for rhs of mod operation, produces DimensionalityError
>>> (-270 * ureg.meters) % 360
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/quantity.py", line 139, in wrapped
    return f(self, *args, **kwargs)
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/quantity.py", line 1406, in __mod__
    magnitude = self._magnitude % other.to(self._units)._magnitude
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/quantity.py", line 716, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/quantity.py", line 665, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/registry.py", line 1044, in convert
    return self._convert(value, src, dst, inplace)
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/registry.py", line 1959, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/registry.py", line 1566, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/home/act3rl/.local/lib/python3.8/site-packages/pint/registry.py", line 1077, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'dimensionless' (dimensionless) to 'meter' ([length])
```
```
# Using meters and quantity for rhs of mod operation produces expected result
>>> (-270 * ureg.meters) % (360 * ureg.meters)
<Quantity(90, 'meter')>
```
```
# Using degrees and no quantity for rhs of mod operator DOES NOT produce a DimensionalityError, 
# and worse the result is very wrong
>>> (-270 * ureg.deg) % 360
<Quantity(20356.4806, 'degree')>
```
```
# Using degrees and quantity for rhs of mod operator, correct result
>>> (-270 * ureg.deg) % (360 * ureg.deg)
<Quantity(90, 'degree')>
```
```
# Using radians and no quantity for rhs of mod operator, DOES NOT produce a DimensionalityError,
# but does produce the expected result
>>> (-270 * ureg.rad) % 360
<Quantity(90, 'radian')>
```
```
# Using radians and quantity for rhs of mod operator, correct result
>>> (-270 * ureg.rad) % (360 * ureg.rad)
<Quantity(90, 'radian')>
```

**Comment by jules-ch** [comment]
Operations with unit 1 (dimensionless) is expected to be in radians.

So `(-270 * ureg.deg) % 360` is equivalent to `(-270 * ureg.deg) % (360 * ureg.radians)`
It produces the expected results.

In fact, if you can rewrite what you expect with the following:

```
>>> (-270 * ureg.deg) % (2*np.pi)
<Quantity(90.0, 'degree')>
```

**Comment by keewis** [comment]
the `DimensionalityError` raised for `(-270 * ureg.m) % 360` is a bit surprising to me: dividing a quantity by a dimensionless quantity works, so modulo (`%`) and floor division (`//`) should work, too (unless I'm missing something).

**Comment by jules-ch** [comment]
I'm gonna close this, rationale is explained https://github.com/hgrecco/pint/issues/943#issuecomment-638195938.
We provided workarounds, do not hesitate to reopen if something was not clear. ❤️

**Comment by jules-ch** [comment]
> Thanks, that does make sense, however it requires a lot of care of users of the system (it's very easy to write bugs). Also, it's not clear to me why deg/rad does not produce a dimensionality error, but meters does.

About the whole degree/radians things, radians is assimilated as a dimensionless Quantity so operation with dimensionless value is going to work & will operate on radians magnitude.
