### ISSUE TITLE
Unit.format_babel doesn't handle division_fmt anymore

### ISSUE THREAD

**Issue by zobac** [hgrecco/pint#1632]
Hi there

Env: Python3.11.0 
OS: Windows 10
Pint: 0.20
Babel: 2.10.3

Unit.format_babel() works fine when handling units with no division format, but crashes for units with division.  I suspect something has changed in the babel.Locale_data object.

```
import pint
ureg = pint.UnitRegistry(fmt_locale='sys')
ureg.Unit('m').format_babel()
'meter'
ureg.Unit('m / s').format_babel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Envs\pintTest\Lib\site-packages\pint\facets\formatting\objects.py", line 227, in format_babel
    return units.format_babel(spec, registry=self._REGISTRY, **kwspec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Envs\pintTest\Lib\site-packages\pint\util.py", line 466, in format_babel
    return format_unit(self, spec, registry=registry, **kwspec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Envs\pintTest\Lib\site-packages\pint\formatting.py", line 413, in format_unit
    return fmt(unit, registry=registry, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Envs\pintTest\Lib\site-packages\pint\formatting.py", line 229, in format_default
    return formatter(
           ^^^^^^^^^^
  File "E:\Envs\pintTest\Lib\site-packages\pint\formatting.py", line 368, in formatter
    neg_ret = _join(division_fmt, neg_terms)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Envs\pintTest\Lib\site-packages\pint\formatting.py", line 44, in _join
    if not __JOIN_REG_EXP.search(fmt):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'LocaleDataDict'

You get the same result if you use a different separator:

reg.Unit('m per s').format_babel()

same error as above...
```

format_babel worked fine in pint 0.17 with no babel package installed.

**Comment by jules-ch** [comment]
Pint handles babel version <= 2.8 for now

**Comment by zobac** [comment]
Awesome.  Thanks.

**Comment by jules-ch** [comment]
Does it works, I'm closing. Feel free to reopen :)
