### ISSUE TITLE
pint-convert does not work anymore after freezing UnitDefinition

### ISSUE THREAD

**Issue by jules-ch** [hgrecco/pint#1646]
Since last releases, UnitDefinition has been frozen but pint-convert script was mutating it to inject correlation uncertainties between constant.

**Comment by surfaceowl** [comment]
Confirmed - and there are some other complications relating to the uncertainties library (which appears to also be required to use pint), when using older python versions as well.

**steps to recreate:**  setup separate virtual environments for python 3.11, 3.10, and 3.10, pip install pint & uncertainties into each one.  

**Results using the 2nd example from the docs** found here:  [https://pint.readthedocs.io/en/stable/dev/pint-convert.html?highlight=pint-convert](https://pint.readthedocs.io/en/stable/dev/pint-convert.html?highlight=pint-convert)<br>

**using python 3.11**
```
(venv) surfaceowl ~/dev/python_jupyter_scratch $ pint-convert --sys US 102kg
Traceback (most recent call last):
  File "/home/chris/dev/python_jupyter_scratch/venv/bin/pint-convert", line 109, in <module>
    ureg._units["R_inf"].converter.scale = R_i
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'scale'
```

**using python 3.10**
```
surfaceowl ~/dev/python_jupyter_scratch $ . venv_310/bin/activate
(venv_310) surfaceowl ~/dev/python_jupyter_scratch $ pint-convert --sys US 102kg
Traceback (most recent call last):
  File "/home/chris/dev/python_jupyter_scratch/venv_310/bin/pint-convert", line 99, in <module>
    (R_i, g_e, m_u, m_e, m_p, m_n) = uncertainties.correlated_values_norm(
AttributeError: module 'uncertainties' has no attribute 'correlated_values_norm'
```

**using python 3.9**
```
(venv_39) surfaceowl ~/dev/python_jupyter_scratch $ pint-convert --sys US 102kg
Traceback (most recent call last):
  File "/home/chris/dev/python_jupyter_scratch/venv_39/bin/pint-convert", line 99, in <module>
    (R_i, g_e, m_u, m_e, m_p, m_n) = uncertainties.correlated_values_norm(
AttributeError: module 'uncertainties' has no attribute 'correlated_values_norm'
```

**Comment by jakeogh** [comment]
Using git-latest, I'm getting FrozenInstanceError on py 3.10.11 as well (I think this is expected until the code is refactored):

```
$ python --version
Python 3.10.11

$ pint-convert --sys US 102kg
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/pint-convert", line 109, in <module>
    ureg._units["R_inf"].converter.scale = R_i
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'scale'
```
