### ISSUE TITLE
pint preprocessor skipped by .to() and .m_as()

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [hgrecco/pint#1687]
I'm doing some work with currency symbols and conversions, but I've had to do extra work to step around pint's attempts to interpret M as Molarity, which I can accept.  But after doing that work (using a pre-processor), things are back to where they started when I use .to() or .m_as() conversions.

My question is: should I know that strings passed to .to() and .m_as() are presumed to be already pre-processed and will not be pre-processed further?  If so, where does it say that in the documentation?  If I should be placing my pre-processor higher up the Pint processing food-chain, where is that explained?  If .to() and .m_as() should call the preprocessor on their inputs, here's a test case for you.

Note that the 2nd-to-last line shows Pint happily converting 1234567 EUR to 12.34567 M€ (which is expected).
The last line shows Pint choking on converting that number explicitly to 'M€', which it can properly understand as shown in the 2nd print statement.

```
import re
import pint
from openscm_units import unit_registry
import pandas as pd

# openscm_units doesn't make it easy to set preprocessors.  This is one way to do it.
unit_registry.preprocessors=[
    lambda s3: translate_currency_symbols(s3)
]

ureg = unit_registry
pint.set_application_registry(ureg)

pint.Quantity = ureg.Quantity
pint.Unit = ureg.Unit
pint.Measurement = ureg.Measurement
pint.Context = ureg.Context

Q_ = ureg.Quantity

currency_dict = {
    # 'US$':'USD', NOTE: don't try to re-define USD...it leads to infinite recursion
    '€':'EUR',
    '¥':'JPY', # 円 / 圓
    '£':'GBP',
    '元':'CNY', # ¥
    'A$':'AUD',
    'C$':'CAD',
    'HK$':'HKD',
    'S$':'SGD',
    'SKr':'SEK',
    '₩':'KRW', # 원/ 圓
    'NKr':'NOK',
    'NZ$':'NZD',
    '₹':'INR',
    'NT$':'TWD',
    'R':'ZAR',
    'R$':'BRL',
    'DKr':'DKK',
    'zł':'PLN',
    '฿':'THB',
    '₪':'ILS',
    'Rp':'IDR',
    'Kč':'CZK',
    'د.إ':'AED',
    '₺':'TRY',
    '₴':'HRV',
    '₦':'NGN'
}

ureg.define("USD = [currency] = $")
for currency_symbol, currency_abbrev in currency_dict.items():
    ureg.define(f"{currency_abbrev} = nan USD = {currency_symbol}")
# Currencies that don't have symbols are added one by one
ureg.define("CHF = nan USD")
ureg.define("MXN = nan USD") # $ abbreviation is ambiguous

currency_keep_regexp = re.compile(fr"({'|'.join([cur_abbrev for cur_abbrev in currency_dict.values()])})")
currency_split_regexp = re.compile(fr"(\$|US\$|{'|'.join([re.escape(currency_symbol) for currency_symbol in currency_dict])})")

def translate_currency_symbols_1(text):
    split_text = re.split(currency_split_regexp, text)
    if len(split_text) <= 1:
        return text
    if len(split_text) & 1 and split_text[-1] != '':
        split_text.append('')
    pairs = zip(split_text[::2], split_text[1::2])
    retval = ''.join(map(lambda x: f"{x[0]}{'USD' if x[1]=='$' or x[1]=='US$' else currency_dict.get(x[1], '')}", pairs))
    # print(f"{text} -> {split_text} -> {retval}")
    return retval

def translate_currency_symbols(text):
    keep_text = re.split(currency_keep_regexp, text)
    if len(keep_text) <= 1:
        return translate_currency_symbols_1(text)
    if len(keep_text) & 1 and keep_text[-1] != '':
        keep_text.append('')
    pairs = zip(keep_text[::2], keep_text[1::2])
    retval = ''.join([inner for outer in pairs for inner in [translate_currency_symbols_1(outer[0]), outer[1]]])
    # print(f"{text} -> {keep_text} -> {retval}")
    return retval

#             currency fx_quote  fx_rate
# report_date                           
# 2021-12-31       CHF      EUR     1.01
# 2021-12-31       USD      EUR     0.94
# 2021-12-31       SEK      EUR     0.09
# 2022-03-31       JPY      EUR   0.0071
# 2021-12-31       GBP      EUR     1.13
# 2021-12-31       KRW      EUR  0.00074
# 2021-12-31       NOK      EUR    0.096
# 2021-12-31       JPY      EUR   0.0071
# 2021-03-31       JPY      EUR   0.0071

def convert_prefix_to_scalar(x):
    pint_unit_tuple = ureg.parse_unit_name(x)
    if pint_unit_tuple == ():
        raise KeyError(f"unit {x} not found in registry")
    prefix, unit, suffix = pint_unit_tuple[0]
    return unit, ureg._prefixes[prefix].value if prefix else 1.0

fx_df = pd.DataFrame({'currency': ['CHF', 'USD', 'SEK', 'JPY', 'GBP', 'KRW', 'NOK', 'gigaJPY', 'JPY', ],
                      'fx_quote': ['EUR', 'EUR', 'EUR', 'EUR', 'EUR', 'EUR', 'EUR', 'megaEUR', 'EUR', ],
                      'fx_rate': [1.01, 0.94, 0.09, 0.0071, 1.13, 0.00074, 0.96, 7.1, 0.0071, ]},
                     index=pd.Index(['2021-12-31', '2021-12-31', '2021-12-31', '2022-03-31', '2021-12-31', '2021-12-31', '2021-12-31', '2021-12-31', '2021-03-31', ], name='report_date'))
fx_df = fx_df.assign(currency_tuple=lambda x: x['currency'].map(convert_prefix_to_scalar),
                     fx_quote_tuple=lambda x: x['fx_quote'].map(convert_prefix_to_scalar))
fx = pint.Context('FX')
# FIXME: These simple rules don't take into account different conversion rates at different time periods.
fx_df.apply(lambda x: fx.redefine(f"{x.currency_tuple[0]} = {x.fx_rate * x.fx_quote_tuple[1] / x.currency_tuple[1]} {x.fx_quote_tuple[0]}")
            if x.currency != 'USD' else fx.redefine(f"{x.fx_quote_tuple[0]} = {x.currency_tuple[1]/(x.fx_rate * x.fx_quote_tuple[1])} {x.currency_tuple[0]}"),
            axis=1)
ureg.add_context(fx)
ureg.enable_contexts('FX')

print(f"ureg('MEUR') = {ureg('MEUR')}")
print(f"ureg('M€') = {ureg('M€')}")
xx = ureg('1234567 €')
print(f"xx = {xx}")
print(f"xx.to('megaEUR') = {xx.to('megaEUR')}")
print(f"xx:#~P = {xx:#~P}")
print(f"xx.to('M€') = {xx.to('M€')}")
```

The error message is:
```
Traceback (most recent call last):
  File "/Users/michael/Dropbox/My Mac (MacBook-Pro.local)/Documents/GitHub/MichaelTiemannOSC/ITR/examples/pint-currency.py", line 122, in <module>
    print(f"xx.to('M€') = {xx.to('M€')}")
  File "/Users/michael/miniconda3/envs/itr_env_vanilla/lib/python3.9/site-packages/pint/facets/plain/quantity.py", line 522, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "/Users/michael/miniconda3/envs/itr_env_vanilla/lib/python3.9/site-packages/pint/facets/plain/quantity.py", line 471, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/Users/michael/miniconda3/envs/itr_env_vanilla/lib/python3.9/site-packages/pint/facets/plain/registry.py", line 911, in convert
    return self._convert(value, src, dst, inplace)
  File "/Users/michael/miniconda3/envs/itr_env_vanilla/lib/python3.9/site-packages/pint/facets/context/registry.py", line 393, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/Users/michael/miniconda3/envs/itr_env_vanilla/lib/python3.9/site-packages/pint/facets/nonmultiplicative/registry.py", line 206, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/Users/michael/miniconda3/envs/itr_env_vanilla/lib/python3.9/site-packages/pint/facets/plain/registry.py", line 944, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'EUR' ([currency]) to 'molar' ([substance] / [length] ** 3)
```

Wisdom and guidance appreciated!

**Comment by OrangeChannel** [comment]
FWIW this affects the new "%" percent sign pre-processor too and was brought up in that PR. The .to() string should have the same pre-processors applied IMO.

**Comment by MichaelTiemannOSC** [comment]
Here's a patch:

```
diff --git a/pint/util.py b/pint/util.py
index 440ac5e..9cc6d2d 100644
--- a/pint/util.py
+++ b/pint/util.py
@@ -899,6 +899,8 @@ def to_units_container(
         return unit_like._units
     elif str in mro:
         if registry:
+            for p in registry.preprocessors:
+                unit_like = p(unit_like)
             return registry._parse_units(unit_like)
         else:
             return ParserHelper.from_string(unit_like)
```

**Comment by hgrecco** [comment]
I am not sure I want to run the preprocessors on every `to` operation. I am afraid this will have a really bad impact on performance. Any options?

**Comment by MichaelTiemannOSC** [comment]
Does it make sense to follow the pattern of re.compile, whereby a `to` string can be compiled/cached for faster performance?

**Comment by andrewgsavage** [comment]
could you have different contexts for each date to deal with different conversion rates at different time periods?
