### ISSUE TITLE
Self defined percent unit fails conversion to dimensionless in some cases

### ISSUE THREAD

**Issue by pkaila** [hgrecco/pint#1688]
I tried to define a 'percent' unit in code in a similar fashion it is defined in the default_en.txt in [this commit](https://github.com/hgrecco/pint/commit/c69c4df91afb61de6ea6295f015e2bc035b8dfcf). It seemed to work ok, except when manually creating a Quantity with the new 'percent' unit `Quantity(5, ureg('percent'))`. The creation of the Quantity succeeds, but converting it to dimensionless will fail. If the Quantity is created by parsing a string `ureg('5 percent')`, the conversion to dimensionless will succeed. I also tried to define the same unit in a text file and import it from there. The end result was exactly the same. The code snippet below will reproduce the issue and produce the stacktrace also listed below.

Pint version is 0.20.1
Python version is 3.11.1

```python
from pint import UnitRegistry, Quantity
ureg = UnitRegistry()
ureg.define('percent = 0.01 = %')
a = ureg('5 percent')
b = Quantity(5, ureg('percent'))
assert a == b
a.to('') # This will print <Quantity(0.05, 'dimensionless')> as expected
b.to('') # This fails in an assertion error
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/plain/quantity.py", line 522, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/plain/quantity.py", line 471, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/plain/registry.py", line 911, in convert
    return self._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/context/registry.py", line 393, in _convert
    return super()._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/nonmultiplicative/registry.py", line 194, in _convert
    src_offset_unit = self._validate_and_extract(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/nonmultiplicative/registry.py", line 124, in _validate_and_extract
    nonmult_units = [
                    ^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/nonmultiplicative/registry.py", line 125, in <listcomp>
    (u, e) for u, e in units.items() if not self._is_multiplicative(u)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/virtualenv/lib/python3.11/site-packages/pint/facets/nonmultiplicative/registry.py", line 115, in _is_multiplicative
    assert len(names) == 1
           ^^^^^^^^^^^^^^^
AssertionError
```

**Comment by OrangeChannel** [comment]
You are importing `Quantity` wrong. You must use `Quantity = ureg.Quantity` after creating the registry.

Also, even though it's not wrong IMO you should be making quantities with `b = Quantity(5, 'percent')` or `b = Quantity(5, ureg.percent)` so that the second input is an actual unit, not a quantity.

**Comment by pkaila** [comment]
Thank you for pointing my mistake. It works now as expected.
