### ISSUE TITLE
Unexpected error with get_dimensionality() 

### ISSUE THREAD

**Issue by sebakahn** [hgrecco/pint#1716]
## Description

If I input an unsupported dimension for `ureg.get_dimensionality()`, I get an unexpected error:
`KeyError` instead of `UndefinedUnitError` or someting like `UndefinedDimensionError`

## Minimal code example

``` python
from pint import UnitRegistry
ureg =  UnitRegistry(system="SI")
ureg.get_dimensionality("[bilbo]")
```

I get the following error traceback

```bash

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 643, in get_dimensionality
    return self._get_dimensionality(input_units)
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 660, in _get_dimensionality
    self._get_dimensionality_recurse(input_units, 1, accumulator)
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 675, in _get_dimensionality_recurse
    reg = self._dimensions[key]
KeyError: '[bilbo]'
```

with a generic `KeyError`

Wile putting a wrong unit provide a more informative error log

```python
from pint import UnitRegistry
ureg =  UnitRegistry(system="SI")
ureg.get_dimensionality("bilbo")
```

Nice error log

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 643, in get_dimensionality
    return self._get_dimensionality(input_units)
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 660, in _get_dimensionality
    self._get_dimensionality_recurse(input_units, 1, accumulator)
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 681, in _get_dimensionality_recurse
    reg = self._units[self.get_name(key)]
  File "/home/skahn/miniconda3/envs/flf_system_code/lib/python3.8/site-packages/pint/facets/plain/registry.py", line 588, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'bilbo' is not defined in the unit registry
```

**Comment by sebakahn** [comment]
I treat the error with a simple error redirection

``` python
        try:
            dim = ureg.get_dimensionality(dimension)
        except KeyError:
            raise ValueError(
                f"{dim} is not defined as dimension in the" 
                "pint UnitRegistry"
            )
```

**Comment by sebakahn** [comment]
Any though on that @hgrecco ?

**Comment by hgrecco** [comment]
Indeed, it would be nice to wrap that within a nice error but around `self._dimensions[key]`
