### ISSUE TITLE
Bug: Unexpected type cohersion when calling .magnitude on a Quantity

### ISSUE THREAD

**Issue by matroscoe** [hgrecco/pint#1735]
Depending on how the `Quantity` is made the `Quantity.magnitude` call can force the type back to string even though the internal representation of the Quantity is storing the magnitude as a numeric type. My expectation is that once converted to a numeric it would have been kept that way. 

Steps to reproduce in any python console: 
```python
Python 3.11.1 (main, Jan 12 2023, 22:01:58) [GCC 11.3.0] on linux
>>> from pint import Quantity
>>> x = Quantity('0.0', 'kg') 
>>> x.magnitude
'0.0'
>>> y = Quantity(0.0, 'kg')
>>> y.magnitude
0.0
```

![image](https://user-images.githubusercontent.com/102177474/230240363-4f33a307-f90f-4078-88f9-0255c75c264c.png)

**Comment by dalito** [comment]
The type of the value is not checked in `pint.compat._to_magnitute(...)`. Only for empty strings an error is raised:

```
>>> Quantity("", "kg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dlinke\MyProg_local\gh-dalito\pint\pint\facets\plain\quantity.py", line 239, in __new__
    magnitude = _to_magnitude(
                ^^^^^^^^^^^^^^
  File "C:\Users\dlinke\MyProg_local\gh-dalito\pint\pint\compat.py", line 56, in _to_magnitude
    raise ValueError("Quantity magnitude cannot be an empty string.")
ValueError: Quantity magnitude cannot be an empty string.
```

This bug is also present for arrays:
```
>>> y = Quantity(['0.0', '1.0'], 'kg')
>>> y.m
array(['0.0', '1.0'], dtype='<U3')
```

The solution could be a conversion of non-empty strings to the numeric type specified via `registry.non_int_type`.

**Comment by matroscoe** [comment]
We have implemented a workaround that we have a bit of a wrapper around `Quantity()` so that we force all of the numeric parts to a `float` before we actually create the `Quantity()` but it would be nice for the desired behavior to be defined and to know if this is the intended behavior for `Quantity()` or if it should be converting a string input to a numeric value type.

**Comment by dalito** [comment]
I don't that this is intended behavior. It looks like a oversight to me. Because pint can work with other numeric types (decimal, fractions), the conversion from string to numeric type has to use the `non_int_type` set at registry level. Converting to float is therefore not a general solution.

Another option which I would slightly prefer is to raise an error if a Quantity is initialized with value and unit and the value is of type string (or a list/tuple of strings).

**Comment by hgrecco** [comment]
Short comment first. When building a `Quantity` from a string, you should always use the `ureg.parse_*` methods. This is proven and integrates nicely with `non_int_type`.

Going to @dalito comment. We decided not to type check the magnitude to allow new (possible unknown to pint) numeric types.  But, I would agree to type check against certain types. Feel free to submit a PR.
