### ISSUE TITLE
Should `Axes.get_ylim` return a `pint.Quantity`?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [hgrecco/pint#1736]
When setting up pint with Matplotlib, we'd like to be able to compare data with the ylim (or xlim) of the graph. 
However, `ax.get_ylim()` does not return a pint.Quantity but floats.

This makes it impossible to compare the ydata with the y limits and breaks some matplotlib extensions like `matplotx`

Is there an easy way to fix this?

```python
import matplotlib.pyplot as plt
import pint

ureg = pint.UnitRegistry()
ureg.setup_matplotlib()

fig, ax = plt.subplots()

(line,) = plt.plot([0, 1, 2] * ureg.cm, [0, 1, 2] * ureg.cm)

print(ax.get_ylim())   # (-0.1, 2.1)
print(line.get_ydata())   # [0 1 2] centimeter

print(max(ax.get_ylim()[0], line.get_ydata()[-1]))
```

Produces:

```
Traceback (most recent call last):
  File "c:\Projects\test.py", line 16, in <module>
    print(max(ax.get_ylim()[0], line.get_ydata()[-1]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remidm\AppData\Roaming\Python\Python311\site-packages\pint\facets\plain\quantity.py", line 1509, in <lambda>
    __gt__ = lambda self, other: self.compare(other, op=operator.gt)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remidm\AppData\Roaming\Python\Python311\site-packages\pint\facets\plain\quantity.py", line 102, in wrapped
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remidm\AppData\Roaming\Python\Python311\site-packages\pint\facets\plain\quantity.py", line 1487, in compare
    raise ValueError(
ValueError: Cannot compare PlainQuantity and <class 'numpy.float64'>
```

**Comment by dopplershift** [comment]
What's able to be returned from matplotlib is only something that can be solved on the matplotlib side through its support for plugging in unit frameworks. You'll have to ask that [over there](https://github.com/matplotlib/matplotlib/issues).

**Comment by RemDelaporteMathurin** [comment]
Ok, I didn't know if there was some monkey patching going on in pint or not.

**Comment by hgrecco** [comment]
I am closing this for the time being. Feel free to reopen.
