### ISSUE TITLE
Changing `default_format` in `__init__` causes unrelated unit change error in `_after_init`

### ISSUE THREAD

**Issue by peterhs73** [hgrecco/pint#1869]
I want to create a custom subclass of the `UnitRegistry` to change some of the default behavior, including the default format. However, it appears that causes an error in `_after_init`. What's a recommended way to do this other than instantiate first? 

```python
import pint
class MyRegistry(pint.UnitRegistry):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.default_format = '~'
MyRegistry()
```

The code above gives an error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 138, in __call__
    obj._after_init()
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/system/registry.py", line 78, in _after_init
    super()._after_init()
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/group/registry.py", line 64, in _after_init
    super()._after_init()
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 307, in _after_init
    loaded_files = self.load_definitions(path, True)
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 553, in load_definitions
    self._helper_dispatch_adder(definition)
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 451, in _helper_dispatch_adder
    adder_func(definition)
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/system/registry.py", line 96, in _add_system
    self.System.from_definition(sd)
  File "/Users/petersun/miniconda3/envs/pint/lib/python3.10/site-packages/pint/facets/system/objects.py", line 179, in from_definition
    raise ValueError(
ValueError: The old unit meter must be a root unit in order to be replaced by new unit bohr
```

**Comment by peterhs73** [comment]
Turns out the `_after_init()` should be modified instead.
``` python
def _after_init(self):
    """Set the default format."""

    super()._after_init()
    self.default_format = "~P"
```
