### ISSUE TITLE
wraps decorator won't accept quantities converted with to() using V for volts when  not uising float as non_int_type

### ISSUE THREAD

**Issue by PlasmaHH** [hgrecco/pint#1907]
Running this little example that was condensed from a codepath in an application:

```python
import pint
import decimal

units = pint.UnitRegistry( non_int_type = decimal.Decimal )
v3 = units("3.3V")
v3 = v3.to("V")

@units.wraps(None,("V"),strict=False)
def func( v ):
    print(f"{v=}")

print(f"{v3=}")
func(v3)
```

leads to the error

```
> ./tpint.py 
v3=<Quantity(3.3, 'volt')>
Traceback (most recent call last):
  File "/home/plasmahh/src/cxx/./tpint.py", line 16, in <module>
    func(v3)
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/registry_helpers.py", line 289, in wrapper
    new_values, new_kw, values_by_name = converter(
                                         ^^^^^^^^^^
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/registry_helpers.py", line 151, in _converter
    values[ndx] = ureg._convert(
                  ^^^^^^^^^^^^^^
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/facets/context/registry.py", line 404, in _convert
    return super()._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/facets/nonmultiplicative/registry.py", line 254, in _convert
    return super()._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/facets/plain/registry.py", line 1060, in _convert
    factor = self._get_conversion_factor(src, dst)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/facets/plain/registry.py", line 841, in _get_conversion_factor
    factor, _ = self._get_root_units(src / dst)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/facets/plain/registry.py", line 880, in _get_root_units
    self._get_root_units_recurse(input_units, 1, accumulators)
  File "/home/plasmahh/.local/lib/python3.11/site-packages/pint/facets/plain/registry.py", line 943, in _get_root_units_recurse
    accumulators[None] *= reg.converter.scale**exp2
                          ~~~~~~~~~~~~~~~~~~~^^~~~~
TypeError: unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
```

Using that same code with other basic units like ampere doesn't lead to the error. I have the suspicion it happens whenever a unit is involved that has no the exponent 1 (e.g. -1)

**Comment by dalito** [comment]
Which version of pint did you use? I could not reproduce the error for master or 0.23.

**Comment by PlasmaHH** [comment]
> Which version of pint did you use? I could not reproduce the error for master or 0.23.

0.23 as installed via pip

**Comment by dalito** [comment]
I forgot to copy the line `v3 = v3.to("V")`. If it is absent there is not exception; with the line I get the same exception. 

Here is a slightly changed example where commenting out the marked line causes the exception. This is strange.

```python
import pint
import decimal

units = pint.UnitRegistry( non_int_type = decimal.Decimal )

@units.wraps(None,("V"),strict=False)
def func( v ):
    print(f"{v=}")

v3 = units("3.3V")
print(f"{v3=}")
func(v3)  # <- comment out to cause exception at func(v4)

v4 = v3.to("V")
print(f"{v4=}")
func(v4)
assert v3==v4
```

**Comment by PlasmaHH** [comment]
It seems that even though the registry has non_int_type decimal set, there are ParseHelper objects created with non_int_type float... poking around in the codebase I see a path going through util.py to_units_container calling ParserHelper.from_string without any non_int_type because the passed registry is None which in turn gets passed down from _parse_wrap_args of registry_helpers.py which is called by wrap() in this line:

```python
converter = _parse_wrap_args(args)
```

changing that line to 
```python
converter = _parse_wrap_args(args,ureg)
```

which fixes the issue for me, though I am not sure if its the intended thing, conceptually.
