### ISSUE TITLE
Pint should validate aliases

### ISSUE THREAD

**Issue by dalito** [hgrecco/pint#1918]
Currently it is possible to define invalid and unusable aliases. In contrast to unit names, alias names are obviously not validated.

```python
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] on win32
>>> import pint
>>> pint.__version__
'0.23'
>>> ureg = pint.UnitRegistry()
>>> ureg.define("@alias meter = my'dog")
>>> ureg("m").to("my'dog")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dlinke\MyProg_local\gh-dalito\ucumvert\.venv\Lib\site-packages\pint\facets\plain\quantity.py", line 526, in to
    other = to_units_container(other, self._REGISTRY)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dlinke\MyProg_local\gh-dalito\ucumvert\.venv\Lib\site-packages\pint\util.py", line 1046, in to_units_container
    return registry.parse_units_as_container(unit_like)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dlinke\MyProg_local\gh-dalito\ucumvert\.venv\Lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 70, in parse_units_as_container
    return super().parse_units_as_container(input_string, as_delta, case_sensitive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dlinke\MyProg_local\gh-dalito\ucumvert\.venv\Lib\site-packages\pint\facets\plain\registry.py", line 1204, in parse_units_as_container
    return self._parse_units_as_container(input_string, as_delta, case_sensitive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dlinke\MyProg_local\gh-dalito\ucumvert\.venv\Lib\site-packages\pint\facets\plain\registry.py", line 1239, in _parse_units_as_container
    cname = self.get_name(name, case_sensitive=case_sensitive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dlinke\MyProg_local\gh-dalito\ucumvert\.venv\Lib\site-packages\pint\facets\plain\registry.py", line 647, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'my' is not defined in the unit registry
>>>ureg("m").to("my")  # So is maybe "my" defined by wrong parsing?
(...)
pint.errors.UndefinedUnitError: 'my' is not defined in the unit registry

```

**Comment by hgrecco** [comment]
I agree. Alias and unit names must be validated. I think they must follow the same rules as python identifiers.

**Comment by dalito** [comment]
The unit name are already properly validated. So validation code is already written just not applied to aliases.

**Comment by hgrecco** [comment]
indeed! Will fix it!

**Comment by hgrecco** [comment]
The code is [there already ](https://github.com/hgrecco/pint/blob/0f24b6f017d5bca318b6364212ba879c80386cb3/pint/errors.py#L60) Just need to swap the function for `is_valid_unit_alias`. Not sure why it is `_no_space` instead of `str.isidentifier`. I will try to look at the history to see if there was any reason that I should tackle before.

But I agree with you, an alias should follow the same rule as a unit name.

**Comment by hgrecco** [comment]
It turns out it is not so easy. Some alias that we want to have like `°C` are not valid identifiers. We will need to improve the function currently named `_no_space`. What else we need to check in addition that there are no spaces?

```python
>>> str.isidentifier("°C")
False
```
