### ISSUE TITLE
Failure to convert between dimensionally inconsistent Quantities within allowing Context 

### ISSUE THREAD

**Issue by dwr-zroy** [hgrecco/pint#1924]
When attempting to convert between quantities that are compatible within a `Context` (but would otherwise be inconsistent), a `DimensionalityError` is raised. The example below utilizes the `chemistry` context from `default_en.txt`. 

The `Context` is being correctly used, but the error is unexpectedly raised. It is possible to induce a `ZeroDivisionError` if the parameters to the context are set where one would occur. 

I used the `chemistry` context to demonstrate. I attempt to convert `1 mole` to it's equivalent `1 mole / liter`. This can be done in the chemistry context if the `volume` parameter is given.

## Environment
Let me know if this isn't reproduceable. I used the following to create a new `conda` environment:
`conda create -n pint_testing python=3.11.7 pint=0.23 -c conda-forge -y`

## Code Example
```
import pint

ureg = pint.UnitRegistry()


@ureg.with_context("chem", volume=1)
def foo():
    """Uses chem context from default_en.txt, lines 805 to 833, in tag 0.23
    """
    value = 1.0 * ureg.moles
    convert = value.to("moles / liter")  # raises error
    return convert


bar = foo()
```

### Parameter `volume` = 1
Error when the parameter `volume`  equals `1`  (as it does above):

```
(pint_testing) PS C:\Users\zroy\Documents\_Python\sandbox> & C:/Users/zroy/AppData/Local/miniconda3/envs/pint_testing/python.exe c:/Users/zroy/Documents/_Python/sandbox/sandbox/units/__init__.py
Traceback (most recent call last):
  File "c:\Users\zroy\Documents\_Python\sandbox\sandbox\units\__init__.py", line 26, in <module>
    bar = foo()
          ^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\registry.py", line 354, in wrapper
    return func(*values, **wrapper_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zroy\Documents\_Python\sandbox\sandbox\units\__init__.py", line 22, in foo
    convert = value.to("moles / liter")  # raises error
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 528, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 472, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\registry.py", line 1028, in convert
    return self._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\registry.py", line 404, in _convert
    return super()._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 254, in _convert
    return super()._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\registry.py", line 1063, in _convert
    raise factor
pint.errors.DimensionalityError: Cannot convert from 'mole' ([substance]) to 'mole / liter' ([substance] / [length] ** 3)
```

### Parameter `volume` = 0
Error when the parameter `volume` equals `0`:
```
Traceback (most recent call last):
  File "c:\Users\zroy\Documents\_Python\sandbox\sandbox\units\__init__.py", line 26, in <module>
    bar = foo()
          ^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\registry.py", line 354, in wrapper
    return func(*values, **wrapper_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zroy\Documents\_Python\sandbox\sandbox\units\__init__.py", line 22, in foo
    convert = value.to("moles / liter")  # raises error
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 528, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 472, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\registry.py", line 1028, in convert
    return self._convert(value, src, dst, inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\registry.py", line 400, in _convert
    src = self._active_ctx.transform(a, b, self, src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\objects.py", line 330, in transform
    return self[(src, dst)].transform(src, dst, registry, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\objects.py", line 222, in transform
    return func(registry, value, **self.defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\context\definitions.py", line 54, in <lambda>
    return lambda ureg, value, **kwargs: ureg.parse_expression(
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\registry.py", line 1388, in parse_expression
    return build_eval_tree(gen).evaluate(_define_op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\pint_eval.py", line 383, in evaluate
    return bin_op[op_text](
           ^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 1035, in __truediv__
    return self._mul_div(other, self._truedivide_cast_int, operator.truediv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 103, in wrapped
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 77, in wrapped
    result = f(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 998, in _mul_div
    magnitude = magnitude_op(new_self._magnitude, other._magnitude)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zroy\AppData\Local\miniconda3\envs\pint_testing\Lib\site-packages\pint\facets\plain\quantity.py", line 1025, in _truedivide_cast_int
    return operator.truediv(a, b)
           ^^^^^^^^^^^^^^^^^^^^^^
ZeroDivisionError: float division by zero
```

**Comment by dwr-zroy** [comment]
The following (simplified) example produces the same two errors, depending on the `volume` parameter:

### Parameter `volume = 1.0`
```
import pint

ureg = pint.UnitRegistry()

value = 1.0 * ureg.moles
convert = value.to("moles / liter", "chem", volume=1.0)  # pint.errors.DimensionalityError
```
### Parameter `volume = 0.0`
```
import pint

ureg = pint.UnitRegistry()

value = 1.0 * ureg.moles
convert = value.to("moles / liter", "chem", volume=0.0)  # ZeroDivisionError
```
