### ISSUE TITLE
Compare quantity to zero should not raise ValueError

### ISSUE THREAD

**Issue by david-zwicker** [hgrecco/pint#194]
Currently, pint raises a ValueError if a quantity with a unit is compared to a plain number. This is of course the correct behavior, but I propose that an exception can be made for the special case of comparing a quantity with zero. In this case, the comparison can be resolved for arbitrary units. An example could read:

    >>> import pint
    >>> ureg = pint.UnitRegistry()
    >>> a = 1 * ureg.meter
    >>> a > 1
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pint/quantity.py", line 592, in <lambda>
        __gt__ = lambda self, other: self.compare(other, op=operator.gt)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pint/quantity.py", line 579, in compare
        raise ValueError('Cannot compare Quantity and {0}'.format(type(other)))
    ValueError: Cannot compare Quantity and <type 'int'>
    >>> a > 0
    True

Note the last line, where I changed the result to what I would pint expect to return.

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen.
