### ISSUE TITLE
Pint in python3.13 TypeError: cannot inherit frozen dataclass from a non-frozen one

### ISSUE THREAD

**Issue by mgt16-LANL** [hgrecco/pint#2064]
Hi All, 

Running into an issue using Pint in newly released python3.13:
Pasting the error trace below.
`Python 3.13.0 | packaged by conda-forge | (main, Oct 17 2024, 12:32:35) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pint
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import pint
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/site-packages/pint/__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/site-packages/pint/delegates/__init__.py", line 12, in <module>
    from . import txt_defparser
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/site-packages/pint/delegates/txt_defparser/__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/site-packages/pint/delegates/txt_defparser/defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/site-packages/pint/delegates/txt_defparser/common.py", line 23, in <module>
    @dataclass(frozen=True)
     ~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "/Users/mgt16/mambaforge/envs/test_py/lib/python3.13/dataclasses.py", line 1043, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
                    'non-frozen one')
TypeError: cannot inherit frozen dataclass from a non-frozen one`

Edit: Pint version:
`# packages in environment at /Users/mgt16/mambaforge/envs/test_py:
#
# Name                    Version                   Build  Channel
pint                      0.24.3             pyhd8ed1ab_0    conda-forge`

**Comment by mgt16-LANL** [comment]
Related to PR and previous issue: https://github.com/hgrecco/pint/pull/2037 . Closing.
