### ISSUE TITLE
TypeError in python 3.13

### ISSUE THREAD

**Issue by FFroehlich** [hgrecco/pint#2065]
The following import 
```
from pint import UnitRegistry
```
fails under python 3.13 with error message
```
File ".../venv/lib/python3.13/site-packages/pint/__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File ".../venv/lib/python3.13/site-packages/pint/delegates/__init__.py", line 12, in <module>
    from . import txt_defparser
  File ".../venv/lib/python3.13/site-packages/pint/delegates/txt_defparser/__init__.py", line 12, in <module>
    from .defparser import DefParser
  File ".../venv/lib/python3.13/site-packages/pint/delegates/txt_defparser/defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File ".../venv/lib/python3.13/site-packages/pint/delegates/txt_defparser/common.py", line 23, in <module>
    @dataclass(frozen=True)
     ~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1043, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
                    'non-frozen one')
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

**Comment by amit-chen-ecoplant** [comment]
also experiencing this

**Comment by hgrecco** [comment]
I will be relasing a new version tomorrow

**Comment by nhoover** [comment]
@hgrecco any progress? Thanks

**Comment by jmtts** [comment]
We now also see this showing up on a fresh environment Python 3.12.5.

For anyone that needs a quick workaround: you can pin the flexparser to 0.3.1 (they released the 0.4 version about 9 hours ago)

```
$ pyenv virtualenv 3.12 pint-test
$ pyenv activate pint-test
$ python -m pip install pint
$ python -c "import pint"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/<path>/lib/python3.12/site-packages/pint/__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "/<path>/lib/python3.12/site-packages/pint/delegates/__init__.py", line 12, in <module>
    from . import txt_defparser
  File "/<path>/lib/python3.12/site-packages/pint/delegates/txt_defparser/__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "/<path>/lib/python3.12/site-packages/pint/delegates/txt_defparser/defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File "/<path>/lib/python3.12/site-packages/pint/delegates/txt_defparser/common.py", line 23, in <module>
    @dataclass(frozen=True)
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.pyenv/versions/3.12.5/lib/python3.12/dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.pyenv/versions/3.12.5/lib/python3.12/dataclasses.py", line 1029, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

**Comment by nhoover** [comment]
Using 0.24.4 it's now working for me with python 3.13.0
