### ISSUE TITLE
copying

### ISSUE THREAD

**Issue by emilienkofman** [hgrecco/pint#252]
Hi,

I'm not sure if it is an issue or if it's a misuse of pint, but I noticed this when deepcopying objects (Python 2.7.8)

    import pint
    import copy
    ur = pint.UnitRegistry()
    t = ur("3mF")
    u = copy.deepcopy(t)
    u.to(ur.F)

raises:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/pint/quantity.py", line 241, in to
        other = UnitsContainer(other)
      File "/usr/local/lib/python2.7/dist-packages/pint/unit.py", line 342, in __init__  
        dict.__init__(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pint/quantity.py", line 978, in __iter__
        it_mag = iter(self.magnitude)
    TypeError: 'int' object is not iterable

**Comment by hgrecco** [comment]
Thanks for the report. It seems that there is an error during copy that does not keep the link to the registry.

**Comment by hgrecco** [comment]
Fixed. Thanks!
