### ISSUE TITLE
Calling 'help' causes crash

### ISSUE THREAD

**Issue by MartinThoma** [hgrecco/pint#261]
```python
>>> pint.__version__
'0.6'
>>> ureg = pint.UnitRegistry()
>>> my_size = 1.74*ureg.meter
>>> help(my_size)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/lib/python3.4/pydoc.py", line 1826, in __call__
    self.help(request)
  File "/usr/lib/python3.4/pydoc.py", line 1876, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib/python3.4/pydoc.py", line 1613, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib/python3.4/pydoc.py", line 1606, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/lib/python3.4/pydoc.py", line 376, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/usr/lib/python3.4/pydoc.py", line 1277, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
  File "/usr/lib/python3.4/pydoc.py", line 209, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
  File "/usr/lib/python3.4/inspect.py", line 374, in classify_class_attrs
    homecls = getattr(get_obj, "__objclass__", homecls)
  File "/usr/local/lib/python3.4/dist-packages/pint/unit.py", line 536, in __getattr__
    return self.Quantity(1, item)
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 98, in __new__
    inst._units = inst._REGISTRY.parse_units(units)
  File "/usr/local/lib/python3.4/dist-packages/pint/unit.py", line 1197, in parse_units
    cname = self.get_name(name)
  File "/usr/local/lib/python3.4/dist-packages/pint/unit.py", line 856, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.unit.UndefinedUnitError: '__objclass__' is not defined in the unit registry
```

**Comment by hgrecco** [comment]
This is fixed in develop.
