### ISSUE TITLE
Conversion of Uncertainties

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#291]
I know Uncertainties is still in beta, but this seems like a fundamental bug, I don't see it listed elsewhere, so I figured I'd record it here. I cannot convert Uncertainties.

``` python
>>> x = ureg.Quantity(2, ureg.m).plus_minus(3)
>>> x.to(ureg.ft)
Traceback (most recent call last):
  File "<ipython-input-74-d42046f677e6>", line 1, in <module>
    x.to(ureg.ft)
  File "/Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/quantity.py", line 241, in to
    other = UnitsContainer(other)
  File "/Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/unit.py", line 342, in __init__
    dict.__init__(self, *args, **kwargs)
  File "/Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/quantity.py", line 978, in __iter__
    it_mag = iter(self.magnitude)
TypeError: 'int' object is not iterable

> /Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/quantity.py(978)__iter__()
    977         # Allow exception to propagate in case of non-iterable magnitude
--> 978         it_mag = iter(self.magnitude)
    979         return iter((self.__class__(mag, self._units) for mag in it_mag))
```

**Comment by hgrecco** [comment]
link to #350
