### ISSUE TITLE
Failed: pint.test()

### ISSUE THREAD

**Issue by bs7** [hgrecco/pint#332]
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan 29 2016, 15:20:20) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pint
>>> pint.test()

======================================================================
ERROR: test_issue94 (test_issues.TestIssuesNP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mbt\AppData\Local\Continuum\Anaconda3\envs\test\lib\site-packages\pint\testsuite\test_issues.py", line 413, in test_issue94
    v3 += v2
  File "D:\Users\mbt\AppData\Local\Continuum\Anaconda3\envs\test\lib\site-packages\pint\quantity.py", line 490, in __iadd__
    return self._iadd_sub(other, operator.iadd)
  File "D:\Users\mbt\AppData\Local\Continuum\Anaconda3\envs\test\lib\site-packages\pint\quantity.py", line 334, in _iadd_sub
    self._magnitude = op(self._magnitude, other._magnitude)
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

======================================================================
ERROR: test_integer_div (test_numpy.TestNumpyMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mbt\AppData\Local\Continuum\Anaconda3\envs\test\lib\site-packages\pint\testsuite\test_numpy.py", line 174, in test_integer_div
    a /= b  # Should be integer division
  File "D:\Users\mbt\AppData\Local\Continuum\Anaconda3\envs\test\lib\site-packages\pint\quantity.py", line 628, in __itruediv__
    return self._imul_div(other, operator.itruediv)
  File "D:\Users\mbt\AppData\Local\Continuum\Anaconda3\envs\test\lib\site-packages\pint\quantity.py", line 554, in _imul_div
    self._magnitude = magnitude_op(self._magnitude, other._magnitude)
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

----------------------------------------------------------------------
Ran 692 tests in 11.668s

FAILED (errors=2, skipped=14, expected failures=14)
<unittest.runner.TextTestResult run=692 errors=2 failures=0>
>>>

**Comment by hgrecco** [comment]
This is due to a change in the latest NumPy. It is fixed in master as seen here 
https://travis-ci.org/hgrecco/pint/branches
