### ISSUE TITLE
pint.testsuite.test_docs failing

### ISSUE THREAD

**Issue by onovy** [hgrecco/pint#360]
When I run:
nosetests -v

pint.testsuite.test_docs tests is failing:

```
pint.testsuite.test_docs ... EE.EE.E.EEEEE.E
======================================================================
ERROR: /<<PKGBUILDDIR>>/docs/tutorial.rst
Doctest: tutorial.rst
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2221, in runTest
    test, out=new.write, clear_globs=False)
  File "/usr/lib/python2.7/doctest.py", line 1454, in run
    return self.__run(test, compileflags, out)
  File "/usr/lib/python2.7/doctest.py", line 1331, in __run
    if check(example.want, got, self.optionflags):
  File "/<<PKGBUILDDIR>>/pint/testsuite/helpers.py", line 62, in check_output
    check = super(PintOutputChecker, self).check_output(want, got, optionflags)
TypeError: super() argument 1 must be type, not classobj

======================================================================
ERROR: /<<PKGBUILDDIR>>/docs/numpy.rst
Doctest: numpy.rst
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2221, in runTest
    test, out=new.write, clear_globs=False)
  File "/usr/lib/python2.7/doctest.py", line 1454, in run
    return self.__run(test, compileflags, out)
  File "/usr/lib/python2.7/doctest.py", line 1331, in __run
    if check(example.want, got, self.optionflags):
  File "/<<PKGBUILDDIR>>/pint/testsuite/helpers.py", line 62, in check_output
    check = super(PintOutputChecker, self).check_output(want, got, optionflags)
TypeError: super() argument 1 must be type, not classobj

======================================================================
...

FAILED (errors=11)
ok
```

// And final result is OK

Thanks for fixing.

**Comment by hgrecco** [comment]
I cannot reproduce. My guess is that `nose` is begin too smart and running everything that starts with start instead of using the testsuite that I have defined (which restricts running the doctest in Python 3.5, with pyyaml, serialize, numpy and uncertainties installed)
