### ISSUE TITLE
cryptic error is raised when a unit that doesn't exist is requested

### ISSUE THREAD

**Issue by fmoor** [hgrecco/pint#365]
Both the Exception type and message are very unintuitive. It seems like a ValueError would be more appropriate and that the message should say something about the requested unit not existing. Because AttributeError is so common it should not be the error that is raised in this situation.

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pint
>>> pint.UnitRegistry().Unit('%')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pint\unit.py", line 66, in __new__
    inst._units = inst._REGISTRY.parse_units(units)._units
  File "pint\unit.py", line 1201, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "pint\unit.py", line 1216, in _parse_units
    units = ParserHelper.from_string(input_string)
  File "pint\util.py", line 411, in from_string
    return cls._from_string(input_string)
  File "pint\compat\lrucache.py", line 129, in wrapper
    result = user_function(*args, **kwds)
  File "pint\util.py", line 445, in _from_string
    ret = build_eval_tree(gen).evaluate(cls.eval_token)
AttributeError: 'NoneType' object has no attribute 'evaluate'
>>>

**Comment by hgrecco** [comment]
You are right. But in general that is not the way you should do it. All normal ways to create a unit provide a nice error:
```python
>>> import pint
ureg = pint.Uni>>> ureg = pint.UnitRegistry()
>>> ureg.is_not_defined
Traceback (most recent call last):
...
pint.errors.UndefinedUnitError: 'is_not_defined' is not defined in the unit registry
>>> ureg('is_not_defined')
Traceback (most recent call last):
...
pint.errors.UndefinedUnitError: 'is_not_defined' is not defined in the unit registry
>>> ureg.parse_expression('is_not_defined')
Traceback (most recent call last):
...
pint.errors.UndefinedUnitError: 'is_not_defined' is not defined in the unit registry
```

**Comment by fmoor** [comment]
Only the attribute lookup approach returns a Unit. The other two return Quantity. Creating a Unit from a variable would require `getattr(ureg, unit_name)`. Also `ureg.Quantity()` is documented the natural assumption is that `ureg.Unit()` is also valid. `ureg.Unit(unit_name)` is much nicer than using `getattr`

**Comment by fmoor** [comment]
also `ureg('%')` raises an `AttributeError`

**Comment by hgrecco** [comment]
Agreed!

**Comment by nicola-zen** [comment]
Seems to be fixed now, issue can be closed

```
u.Unit('mhgfds')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\nicola zanardi\desktop\venv\lib\site-packages\pint\unit.py", line 40, in __init__
    self._units = self._REGISTRY.parse_units(units)._units
  File "c:\users\nicola zanardi\desktop\venv\lib\site-packages\pint\registry.py", line 1065, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "c:\users\nicola zanardi\desktop\venv\lib\site-packages\pint\registry.py", line 1264, in _parse_units
    return super()._parse_units(input_string, as_delta)
  File "c:\users\nicola zanardi\desktop\venv\lib\site-packages\pint\registry.py", line 1093, in _parse_units
    cname = self.get_name(name)
  File "c:\users\nicola zanardi\desktop\venv\lib\site-packages\pint\registry.py", line 626, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'mhgfds' is not defined in the unit registry

'mhgfds' is not defined in the unit registry
```

**Comment by MrCreosote** [comment]
`ureg.parse_expression('%')` also results in an `AttributeError` in `0.11`. Not sure if that's expected based on the above.
