### ISSUE TITLE
Can't Open Custom Registry

### ISSUE THREAD

**Issue by hohlraum** [hgrecco/pint#437]
I have a registry file in the cwd called `pint_units.txt`, it can be opened and read with `io.open` but when I try to load it with pint I get the following error:

```
>>> import pint
>>> pint.UnitRegistry('pint_units.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 1411, in __init__
    self._after_init()
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 1221, in _after_init
    super(SystemRegistry, self)._after_init()
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 164, in _after_init
    self.load_definitions(self._filename)
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 353, in load_definitions
    raise ValueError('While opening {0}\n{1}'.format(file, msg))
ValueError: While opening pint_units.txt
While opening constants_en.txt
[Errno 2] No such file or directory: 'constants_en.txt'
```

Note the mismatched file names in the confusing error messages at the end. The result is more straightforward if I use a filename for a file that doesn't exist:

```
>>> pint.UnitRegistry('bogus.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 1411, in __init__

  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 1221, in _after_init
    def _after_init(self):
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 164, in _after_init
    self.load_definitions(self._filename)
  File "/usr/local/lib/python2.7/site-packages/pint/registry.py", line 353, in load_definitions
    msg = getattr(e, 'message', '') or str(e)
ValueError: While opening bogus.txt
[Errno 2] No such file or directory: 'bogus.txt'
```

**Comment by jameswyse** [comment]
Does the `constants_en.txt` file exist in cwd as well? It's @imported in the registry file with `@import constants.txt`

**Comment by hohlraum** [comment]
No. The cwd has only a single file, `pint_units.txt`.

**Comment by hgrecco** [comment]
@hohlraum Double check your definitions file. If you copied the defaults definitions to your custom file, there is a (relative) import to `constants_en.txt`

**Comment by hohlraum** [comment]
That's it. I'd just edited out the unwanted definitions in the default. I overlooked the `@import constants_en.txt` line hidden in there. 

Solution 1: comment out the `@import` statement. Works fine until you need a constant (e.g. contexts)
Solution 2: add a copy of `constants_en.txt` to the cwd. 

BTW this all arose because I needed to deregister a small number of units (see #269). Add another vote for `ureg.undefine()`.

Thanks.

**Comment by jameswyse** [comment]
Yeah I did the same thing because I needed to add `quarters` as a unit of time (1/4 of a year) and couldn't override the default (which is a unit of weight)

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen if necessary.
