### ISSUE TITLE
Decimal conversion with offset

### ISSUE THREAD

**Issue by txxia** [hgrecco/pint#452]
Hello,
I started using pint as it supports Decimal types, but seems like it's not handled in conversion with offset.

Here is an example:
```python
>>> from pint import UnitRegistry
>>> from decimal import Decimal
>>> UR = UnitRegistry()
>>> q = UR.Quantity(Decimal('0'), 'K')
>>> q
<Quantity(0, 'kelvin')>
>>> q.to('celsius')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pint\quantity.py", line 263, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pint\quantity.py", line 231, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pint\unit.py", line 1026, in convert
    return self._convert(value, src, dst, inplace)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pint\unit.py", line 1134, in _convert
    value = self._units[u].converter.from_reference(value, inplace)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pint\converters.py", line 80, in from_reference
    value = (value - self.offset) / self.scale
TypeError: unsupported operand type(s) for -: 'decimal.Decimal' and 'float'
```

**Comment by hgrecco** [comment]
This should be fixed! #

**Comment by onealj** [comment]
What is the expected behavior? If a quantity has a Decimal magnitude, what should be the type of the quantity returned by a converter function?
# Decimal, unsafely converting floats to Decimal as necessary
# Decimal, duplicating the converter code to handle Decimal math and float math differently
# float, drop down to lowest common denominator

**Comment by hgrecco** [comment]
We already support `float` and `Fraction` for multiplicative convertors. We could do the same for offset convertors. Another question is if we should reparse the definition (in a Lazy way) to do it properly.

**Comment by pinkynrg** [comment]
Any progress on this issue?

**Comment by hgrecco** [comment]
Not really. A PR would be welcomed.

**Comment by hgrecco** [comment]
This has been solved by the PR, feel free to reopen if needed.
