### ISSUE TITLE
Defining multiple units to ureg at the same time

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [hgrecco/pint#462]
I'm having a problem defining units with ureg.define  . I think it would be beneficial if multiple units can be defined in one ureg.define call just like if a config file were being used.
When I run:
```python
ureg.define('''
us_dollar = [currency] = $

sheet_unit = [material_sheet]

part_unit = [cutout_part]
''')
```
sheet_unit and part_unit are not defined and an error is not thrown for an invalid input.  
When I run:
```python
ureg.define('us_dollar = [currency] = $')

ureg.define('sheet_unit = [material_sheet]')

ureg.define('part_unit = [cutout_part]')
```
All the units are defined so it is not a problem with each line's syntax.  
Here is my test script if you want to try it (running python 3.5)
```python
import pint
ureg = pint.UnitRegistry()
ureg.define('''
us_dollar = [currency] = $
sheet_unit = [material_sheet]
part_unit = [cutout_part]
''')

# ureg.define('us_dollar = [currency] = $')
# ureg.define('sheet_unit = [material_sheet]')
# ureg.define('part_unit = [cutout_part]')

ureg('1$')
ureg('1us_dollar')
ureg('1sheet_unit')
```
and here is my error message
```shell
Traceback (most recent call last):
  File "try.py", line 17, in <module>
    ureg('1sheet_unit')
  File "/Users/williamrusnack/Documents/virtualenv_all/Formulate/lib/python3.5/site-packages/pint/unit.py", line 1271, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x : self._eval_token(x, case_sensitive=case_sensitive,
  File "/Users/williamrusnack/Documents/virtualenv_all/Formulate/lib/python3.5/site-packages/pint/pint_eval.py", line 83, in evaluate
    return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
  File "/Users/williamrusnack/Documents/virtualenv_all/Formulate/lib/python3.5/site-packages/pint/pint_eval.py", line 92, in evaluate
    return define_op(self.left)
  File "/Users/williamrusnack/Documents/virtualenv_all/Formulate/lib/python3.5/site-packages/pint/unit.py", line 1272, in <lambda>
    **values))
  File "/Users/williamrusnack/Documents/virtualenv_all/Formulate/lib/python3.5/site-packages/pint/unit.py", line 1252, in _eval_token
    case_sensitive=case_sensitive) : 1}))
  File "/Users/williamrusnack/Documents/virtualenv_all/Formulate/lib/python3.5/site-packages/pint/unit.py", line 753, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'sheet_unit' is not defined in the unit registry
```

**Comment by hgrecco** [comment]
Indeed `define` is built in such a way that allows a single definition. You can use `load_definitions` and provide a line iterable. For example,

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.load_definitions('''
... us_dollar = [currency] = $
... sheet_unit = [material_sheet]
... part_unit = [cutout_part]
... '''.split('\n'))
>>> ureg('1$')
1
>>> ureg('1us_dollar')
<Quantity(1, 'us_dollar')>
>>> ureg('1sheet_unit')
<Quantity(1, 'sheet_unit')>
```

**Comment by hgrecco** [comment]
Indeed `define` is built in such a way that allows a single definition. You can use `load_definitions` and provide a line iterable. For example,

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.load_definitions('''
... us_dollar = [currency] = $
... sheet_unit = [material_sheet]
... part_unit = [cutout_part]
... '''.split('\n'))
>>> ureg('1$')
1
>>> ureg('1us_dollar')
<Quantity(1, 'us_dollar')>
>>> ureg('1sheet_unit')
<Quantity(1, 'sheet_unit')>
```

**Comment by BebeSparkelSparkel** [comment]
Currently, I’ve been calling define for every line but this is better.

It would be nice if define throws an error if it gets those multi-line strings or even better just splits them and and loads all the definitions.

Thank you for your help!
