### ISSUE TITLE
append quantities

### ISSUE THREAD

**Issue by martinwk** [hgrecco/pint#467]
Say I have some quantities that I want to put into one array. Without pint and without units, 
I would do something like:
```
array = np.array([_instance.c0 for _instance in instances])
```
However, with Pint this will give 
```
[<Quantity(0.0, 'gram')>, <Quantity(0.0, 'gram')>, <Quantity(0.0, 'gram ')>]
```
while I would like to have something like
```
<Quantity([ 0.  0.  0.], 'gram')>
```
Is there an option in Pint I am missing? I fixed this with some function and the @wraps decorator:
```
    @ureg.wraps('=A',(None, '=A', '=A'))
    def myAppend(self, array, value):
        array_out = np.append(array, value)
        return array_out

    c0 = np.array([]) * ureg('mg/L')
    for _i in instances:
        c0 = self.myAppend(c0, _i.c0)
```
I think it would be nice if the np.append would exhibit this behaviour.

**Comment by hgrecco** [comment]
Yes. If it is an homogenous vector you can just do:
```python
>>> [1, 2, 3, 4] * ureg.gram
```
or 
```python
>>> np.asarray([1, 2,3, 4]) * ureg.gram 
```

**Comment by martinwk** [comment]
Ok I was not really clear on this. 
Say I have a MyClass with attribute c0. At some point I add a value to c0 to different instances of the MyClass 
```
instance1 = MyClass()
instance2 = MyClass ()

instance1.c0 = 1. * ureg.m
instance2.c0 = 2. * ureg.mm

instances = [instance1, instance2]
```
Now I want to create a list with the c0 of all the entries in instances. If I do it with 
```
array =[_instance.c0 for _instance in instances]
```
I get
```
[<Quantity(1.0, 'meter')>, <Quantity(2., 'millimeter')>]

```
But I would like
```
<Quantity([ 1., 2e-3], 'meter')>
```

**Comment by impact27** [comment]
I had the same problem. I used the following function:
Is there a better way to do this?
```
def to_array(value, unit=None):
    def recursion(value, unit):
        if isinstance(value, Q_):
            if unit is not None:
                value = value.to(unit)
            else:
                unit = value.u
            return value.m, unit
        
        elif isinstance(value, (list, tuple)):
            array = []
            for val in value:
                m, unit = recursion(val, unit)
                array.append(m)
            return np.array(array), unit
        else:
            raise RuntimeError("unknown type found")
    return Q_(*recursion(value, unit))
```

**Comment by jthielen** [comment]
I believe this should be resolved by #905 with the through the use of `np.append`.

**Comment by hgrecco** [comment]
Right now append is stripping the units
```python
>>> q = [1,2,3]* ureg.meter
>>> np.append(q, 4)
/Users/grecco/anaconda3/envs/pint-devel/lib/python3.6/site-packages/numpy/core/numeric.py:553: UnitStrippedWarning: The unit of the quantity is stripped when getting __array_struct__ attribute
  return array(a, dtype, copy=False, order=order, subok=True)
array([1, 2, 3, 4])
```

**Comment by jthielen** [comment]
@hgrecco What versions are you using when obtaining that result? On current master branch of pint and v1.17.3 of NumPy, I get the following:

```python
>>> q = [1, 2, 3] * ureg.meter
>>> np.append(q, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in append
  File ".../quantity.py", line 1412, in __array_function__
    return numpy_wrap("function", func, args, kwargs, types)
  File ".../numpy_func.py", line 784, in numpy_wrap
    return handled[func.__name__](*args, **kwargs)
  File ".../numpy_func.py", line 624, in implementation
    *(bound_args.arguments[label] for label in valid_unit_arguments)
  File ".../numpy_func.py", line 99, in unwrap_and_wrap_consistent_units
    args, _ = convert_to_consistent_units(*args, pre_calc_units=first_input_units)
  File ".../numpy_func.py", line 84, in convert_to_consistent_units
    tuple(convert_arg(arg, pre_calc_units=pre_calc_units) for arg in args),
  File ".../numpy_func.py", line 84, in <genexpr>
    tuple(convert_arg(arg, pre_calc_units=pre_calc_units) for arg in args),
  File ".../numpy_func.py", line 66, in convert_arg
    raise DimensionalityError("dimensionless", pre_calc_units)
pint.errors.DimensionalityError: Cannot convert from 'dimensionless' to 'meter'
>>> np.append(q, 4 * ureg.meter)
<Quantity([1 2 3 4], 'meter')>
```

**Comment by hgrecco** [comment]
Indeed!
