### ISSUE TITLE
Docstring help gives error

### ISSUE THREAD

**Issue by nestor013** [hgrecco/pint#471]
This issue (#261) is back again.
```
In [1]: import sys
In [2]: import pint
In [3]: sys.version
Out[3]: '3.5.2 (default, Nov  7 2016, 11:31:36) \n[GCC 6.2.1 20160830]'
In [4]: pint.__version__
Out[4]: '0.7.2'
In [5]: ureg = pint.UnitRegistry()
In [6]: my_size = 1.74*ureg.meter
In [7]: help(my_size)
---------------------------------------------------------------------------
UndefinedUnitError                        Traceback (most recent call last)
<ipython-input-7-2af0131e757d> in <module>()
----> 1 help(my_size)

/usr/lib/python3.5/_sitebuiltins.py in __call__(self, *args, **kwds)
    101     def __call__(self, *args, **kwds):
    102         import pydoc
--> 103         return pydoc.help(*args, **kwds)

/usr/lib/python3.5/pydoc.py in __call__(self, request)
   1843     def __call__(self, request=_GoInteractive):
   1844         if request is not self._GoInteractive:
-> 1845             self.help(request)
   1846         else:
   1847             self.intro()

/usr/lib/python3.5/pydoc.py in help(self, request)
   1896             else: doc(str, 'Help on %s:', output=self._output)
   1897         elif isinstance(request, Helper): self()
-> 1898         else: doc(request, 'Help on %s:', output=self._output)
   1899         self.output.write('\n')
   1900 

/usr/lib/python3.5/pydoc.py in doc(thing, title, forceload, output)
   1630     try:
   1631         if output is None:
-> 1632             pager(render_doc(thing, title, forceload))
   1633         else:
   1634             output.write(render_doc(thing, title, forceload, plaintext))

/usr/lib/python3.5/pydoc.py in render_doc(thing, title, forceload, renderer)
   1623         object = type(object)
   1624         desc += ' object'
-> 1625     return title % desc + '\n\n' + renderer.document(object, name)
   1626 
   1627 def doc(thing, title='Python Library Documentation: %s', forceload=0,

/usr/lib/python3.5/pydoc.py in document(self, object, name, *args)
    369         try:
    370             if inspect.ismodule(object): return self.docmodule(*args)
--> 371             if inspect.isclass(object): return self.docclass(*args)
    372             if inspect.isroutine(object): return self.docroutine(*args)
    373         except AttributeError:

/usr/lib/python3.5/pydoc.py in docclass(self, object, name, mod, *ignored)
   1269 
   1270         attrs = [(name, kind, cls, value)
-> 1271                  for name, kind, cls, value in classify_class_attrs(object)
   1272                  if visiblename(name, obj=object)]
   1273 

/usr/lib/python3.5/pydoc.py in classify_class_attrs(object)
    204     """Wrap inspect.classify_class_attrs, with fixup for data descriptors."""
    205     results = []
--> 206     for (name, kind, cls, value) in inspect.classify_class_attrs(object):
    207         if inspect.isdatadescriptor(value):
    208             kind = 'data descriptor'

/usr/lib/python3.5/inspect.py in classify_class_attrs(cls)
    387                 pass
    388             else:
--> 389                 homecls = getattr(get_obj, "__objclass__", homecls)
    390                 if homecls not in class_bases:
    391                     # if the resulting object does not live somewhere in the

/usr/lib/python3.5/site-packages/pint/unit.py in __getattr__(self, item)
    373 
    374     def __getattr__(self, item):
--> 375         return self.Unit(item)
    376 
    377     def __getitem__(self, item):

/usr/lib/python3.5/site-packages/pint/unit.py in __new__(cls, units)
     64             inst._units = units
     65         elif isinstance(units, string_types):
---> 66             inst._units = inst._REGISTRY.parse_units(units)._units
     67         elif isinstance(units, _Unit):
     68             inst._units = units._units

/usr/lib/python3.5/site-packages/pint/unit.py in parse_units(self, input_string, as_delta)
   1199             :class:`ValueError` if the expression is invalid.
   1200         """
-> 1201         units = self._parse_units(input_string, as_delta)
   1202         return self.Unit(units)
   1203 

/usr/lib/python3.5/site-packages/pint/unit.py in _parse_units(self, input_string, as_delta)
   1221         many = len(units) > 1
   1222         for name in units:
-> 1223             cname = self.get_name(name)
   1224             value = units[name]
   1225             if not cname:

/usr/lib/python3.5/site-packages/pint/unit.py in get_name(self, name_or_alias, case_sensitive)
    751         candidates = self._dedup_candidates(self.parse_unit_name(name_or_alias, case_sensitive))
    752         if not candidates:
--> 753             raise UndefinedUnitError(name_or_alias)
    754         elif len(candidates) == 1:
    755             prefix, unit_name, _ = candidates[0]

UndefinedUnitError: '__objclass__' is not defined in the unit registry

```

**Comment by willprice** [comment]
Here's a slightly more condensed stacktrace from python 3.6 with pint 0.7.2

```
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> x = 1 * ureg.second
>>> help(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/lib/python3.6/pydoc.py", line 1858, in __call__
    self.help(request)
  File "/usr/lib/python3.6/pydoc.py", line 1911, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib/python3.6/pydoc.py", line 1645, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib/python3.6/pydoc.py", line 1638, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/lib/python3.6/pydoc.py", line 383, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/usr/lib/python3.6/pydoc.py", line 1283, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
  File "/usr/lib/python3.6/pydoc.py", line 206, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
  File "/usr/lib/python3.6/inspect.py", line 400, in classify_class_attrs
    homecls = getattr(get_obj, "__objclass__", homecls)
  File "/usr/lib/python3.6/site-packages/pint/unit.py", line 375, in __getattr__
    return self.Unit(item)
  File "/usr/lib/python3.6/site-packages/pint/unit.py", line 66, in __new__
    inst._units = inst._REGISTRY.parse_units(units)._units
  File "/usr/lib/python3.6/site-packages/pint/unit.py", line 1201, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "/usr/lib/python3.6/site-packages/pint/unit.py", line 1223, in _parse_units
    cname = self.get_name(name)
  File "/usr/lib/python3.6/site-packages/pint/unit.py", line 753, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: '__objclass__' is not defined in the unit registry
```

**Comment by willprice** [comment]
Just pulled `master` at commit `de8fdff91bf25a5066012df1ec75db1034eeae64` and reran the above and I now get help for the `Quantity` class, which I presume is the desired behaviour.

**Comment by nestor013** [comment]
Sorry for the delay,

Works like a charm.

Thanks, and thanks again  to all the people working on this excellent project.
