### ISSUE TITLE
AttributeError when parsing '%'

### ISSUE THREAD

**Issue by AntoineGX** [hgrecco/pint#473]
Hello,

Parsing '%' gives an AttributeError:
```
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg('%')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\pint\unit.py", line 1271, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x : self._eval_token(x, case_sensitive=case_sensitive,
AttributeError: 'NoneType' object has no attribute 'evaluate'
```

Pint version is 0.7.2, running with Python 3.5.1 :: Anaconda 2.5.0 (32-bit).

It would be useful to have this fixed in order to be able to define a percentage unit:
```
ureg.define('percentage = [] = percent = pct = %')
```

**Comment by AntoineGX** [comment]
Sorry, seems like a duplicate of #429

**Comment by hgrecco** [comment]
Closing this in favor of #429
