### ISSUE TITLE
Doctests failing with ureg = pint.UnitRegistry()

### ISSUE THREAD

**Issue by raphaeltimbo** [hgrecco/pint#476]
I am having problems with doctests when using `ureg = pint.UnitRegistry`.

As an example, if I have a test.py file with the following code:

```
def func(a):
    """
    >>> func(2)
    2
    """
    return a
```

If I run `python -m doctest -v test.py` I get:

```
Trying:
    func(2)
Expecting:
    2
ok
1 items had no tests:
    test
1 items passed all tests:
   1 tests in test.func
1 tests in 2 items.
1 passed and 0 failed.
Test passed.
```

But when I modify the script putting ureg at the beggining:

```
from pint import UnitRegistry

ureg = UnitRegistry()

def func(a):
    """
    >>> func(2)
    2
    """
    return a

```

I get the following:

```
Traceback (most recent call last):
  File "/home/raphael/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/raphael/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/raphael/anaconda3/lib/python3.5/doctest.py", line 2778, in <module>
    sys.exit(_test())
  File "/home/raphael/anaconda3/lib/python3.5/doctest.py", line 2768, in _test
    failures, _ = testmod(m, verbose=verbose, optionflags=options)
  File "/home/raphael/anaconda3/lib/python3.5/doctest.py", line 1941, in testmod
    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):
  File "/home/raphael/anaconda3/lib/python3.5/doctest.py", line 924, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/home/raphael/anaconda3/lib/python3.5/doctest.py", line 983, in _find
    if ((inspect.isroutine(inspect.unwrap(val))
  File "/home/raphael/anaconda3/lib/python3.5/inspect.py", line 471, in unwrap
    while _is_wrapper(func):
  File "/home/raphael/anaconda3/lib/python3.5/inspect.py", line 465, in _is_wrapper
    return hasattr(f, '__wrapped__')
  File "/home/raphael/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 375, in __getattr__
    return self.Unit(item)
  File "/home/raphael/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 66, in __new__
    inst._units = inst._REGISTRY.parse_units(units)._units
  File "/home/raphael/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 1201, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "/home/raphael/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 1223, in _parse_units
    cname = self.get_name(name)
  File "/home/raphael/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 753, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: '__wrapped__' is not defined in the unit registry

```

I am using linux ubuntu 16.04 with python 3.5.2 and pint 0.7.2.

**Comment by jhidding** [comment]
This issue can be resolved using:

```
class MyUnitRegistry(UnitRegistry):
    def __getattr__(self, name):
        if name[0] == '_':
            try:
                value = super(MyUnitRegistry, self).__getattr__(name)
                return value
            except pint.errors.UndefinedUnitError as e:
                raise AttributeError()
        else:
            return super(MyUnitRegistry, self).__getattr__(name)
```

The UnitRegistry raises the wrong exception for the `hasattr` function to work correctly.

**Comment by hgrecco** [comment]
This should be fixed using the now available default registry.
