### ISSUE TITLE
numpy arange unsupported

### ISSUE THREAD

**Issue by willprice** [hgrecco/pint#484]
Versions:

* `python`: v3.6.0
* `numpy`: v1.12.0
* `pint`: 0.8.dev0 (commit de8fdff)

```python
import numpy as np
import pint
ureg = pint.UnitRegistry()
x = 1 * ureg.meter

y = np.arange(0, x, 0.1)
```

Results in:
```
Traceback (most recent call last):
  File "pint_test.py", line 7, in <module>
    y = np.arange(0, x, 0.1)
  File "/home/will/src/pint/pint/quantity.py", line 431, in __float__
    raise DimensionalityError(self._units, 'dimensionless')
pint.errors.DimensionalityError: Cannot convert from 'meter' to 'dimensionless'
```

Since one can do `np.linspace(0, x, 10)` without problems I think this is a bug, although I may be misunderstanding and this may be an implication of the stated [numpy support](https://pint.readthedocs.io/en/0.6/numpy.html#support)

**Comment by hgrecco** [comment]
The correct way would be:
```python
y = np.arange(0, 1 * ureg.meter, 0.1 * ureg.meter)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
```
However, this fails (with a different error). The reason is that `linspace` is implemented internally by numpy as a python function with additions and multiplications. `arange` is implemented in C and it does not "properly" dispatch to Pint Quantity methods.

**Comment by masasin** [comment]
Something like `np.array([1 * ureg.meter, 0.1 * ureg.meter])` also fails with that error. Is there any way to mitigate that?

**Comment by hgrecco** [comment]
The problem is that there is no way to tell numpy that we will handle it. The suggested way is 

```python
[1, 0.1] * ureg.meter
```

**Comment by onealj** [comment]
And `np.arange(0, 1, 0.1)*ureg.meter`

On Jun 14, 2017 7:04 PM, "Hernan Grecco" <notifications@github.com> wrote:

The problem is that there is no way to tell numpy that we will handle it.
The suggested way is

[1, 0.1] * ureg.meter

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hgrecco/pint/issues/484#issuecomment-308607690>, or mute
the thread

**Comment by impact27** [comment]
I had the same problem and I had an idea: 

The problem is that if the Quantity objects are ndarrays or similar (which numpy determines by calling `__array_interface__`), numpy will want to transform them to ndarray to do the computation. if they are just some other class, numpy will still work if the class implements arithmetics.

Therefore, by not responding to `__array_*`, numpy will create a range. This also allows to have a numpy array of Quantity. (with dtype object)

```
class myQ_(Q_):
    pass
    def __getattr__(self, item):
        if item == '__array_interface__' or item == '__array_struct__' or item == '__array__':
            raise AttributeError('Nope')

        # if item in self.__handled:
        if item in self._Quantity__handled:
            def fun(*args, **kwargs):
                uf = getattr(np, item)
                return uf(self.m, *args, **kwargs)
            fun.__name__ = item
            return functools.partial(self._Quantity__numpy_method_wrap, fun)
        return super().__getattr__(item)
    

A = myQ_(0, 's')
B = myQ_(1, 's')
C = myQ_(0.1, 's')
#%%
y = np.arange(A, B, C)
```

This code is not working for numpy functions taking more than 1 argument but I thought I would share it.

**Comment by thomaslima** [comment]
Just came across this issue while trying to convert a list of Quantities to a numpy array:
```python
>>> from myproject import Q_
>>> a = Q_(1,'nm')
>>> import numpy as np
>>> np.array([a, a])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
```

**Comment by hgrecco** [comment]
Revisit after #905

**Comment by jthielen** [comment]
Currently, `np.arange` does not support overrides via `__array_function__` (see https://github.com/numpy/numpy/issues/12379), so this is still unresolved by #905.

However, in https://github.com/numpy/numpy/issues/12379, there are comments to the effect that, in principal, `np.arange` should only be used with scalar integers. So, based on that, I would guess that usage with Quantities as arguments may need to be avoided, and instead something like the following used to achieve the desired behavior:

```python
np.arange(0, 1, 0.1) * ureg.meter
```
