### ISSUE TITLE
Unit tests fails with numpy 1.13.1

### ISSUE THREAD

**Issue by onovy** [hgrecco/pint#577]
Refs: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876921

Thanks for fixing.

```
S.S................................................./usr/lib/python2.7/unittest/case.py:340: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
.......S...S............................SSSSSSSSSSS.................S...................................................................................................................................................E.E...E.................................................................................................................................................................................................................................................................................................../build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_quantity.py:287: RuntimeWarning: to_compact applied to non numerical types has an undefined behavior.
  self.assertQuantityAlmostIdentical(q.to_compact(unit=unit),
.......................................F..F..........................................................................................................................................................................
======================================================================
ERROR: test_inplace_exponentiation (pint.testsuite.test_quantity.TestOffsetUnitMath) [with input = ((10, u'degC'), (2, u'')); expected_output = [u'error', (80173.92249999999, u'kelvin**2')]]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/parameterized.py", line 116, in new_method
    return method(self, *param_values)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/parameterized.py", line 137, in newfunc
    return func(*arg, **kwargs)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_quantity.py", line 1165, in test_inplace_exponentiation
    self.assertEqual(op.ipow(in1_cp, in2).units, expected.units)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/quantity.py", line 961, in __ipow__
    self._magnitude **= _to_magnitude(other, self.force_ndarray)
TypeError: unsupported operand type(s) for ** or pow(): 'numpy.ndarray' and 'Quantity'

======================================================================
ERROR: test_inplace_exponentiation (pint.testsuite.test_quantity.TestOffsetUnitMath) [with input = ((10, u'kelvin'), (2, u'')); expected_output = [(100.0, u'kelvin**2'), (100.0, u'kelvin**2')]]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/parameterized.py", line 116, in new_method
    return method(self, *param_values)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/parameterized.py", line 137, in newfunc
    return func(*arg, **kwargs)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_quantity.py", line 1165, in test_inplace_exponentiation
    self.assertEqual(op.ipow(in1_cp, in2).units, expected.units)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/quantity.py", line 961, in __ipow__
    self._magnitude **= _to_magnitude(other, self.force_ndarray)
TypeError: unsupported operand type(s) for ** or pow(): 'numpy.ndarray' and 'Quantity'

======================================================================
ERROR: test_inplace_exponentiation (pint.testsuite.test_quantity.TestOffsetUnitMath) [with input = ((10, u'degC'), (500.0, u'millikelvin/kelvin')); expected_output = [u'error', (16.827061537891872, u'kelvin**0.5')]]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/parameterized.py", line 116, in new_method
    return method(self, *param_values)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/parameterized.py", line 137, in newfunc
    return func(*arg, **kwargs)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_quantity.py", line 1165, in test_inplace_exponentiation
    self.assertEqual(op.ipow(in1_cp, in2).units, expected.units)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/quantity.py", line 961, in __ipow__
    self._magnitude **= _to_magnitude(other, self.force_ndarray)
TypeError: unsupported operand type(s) for ** or pow(): 'numpy.ndarray' and 'Quantity'

======================================================================
FAIL: test_isfinite (pint.testsuite.test_umath.TestFloatingUfuncs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_umath.py", line 617, in test_isfinite
    (self.q1, self.qm, self.qless))
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_umath.py", line 101, in _testn
    self._test1(func, ok_with, raise_with, output_units=None, results=results)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_umath.py", line 85, in _test1
    self.assertQuantityAlmostEqual(qm, res, rtol=rtol, msg=err_msg)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/__init__.py", line 117, in assertQuantityAlmostEqual
    np.testing.assert_allclose(m1, m2, rtol=rtol, atol=atol, err_msg=msg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=0
At isreal with [ 1.  2.  3.  4.] joule
(mismatch 100.0%)
 x: array(False, dtype=bool)
 y: array([ True,  True,  True,  True], dtype=bool)

======================================================================
FAIL: test_isreal (pint.testsuite.test_umath.TestFloatingUfuncs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_umath.py", line 609, in test_isreal
    (self.q1, self.qm, self.qless))
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_umath.py", line 101, in _testn
    self._test1(func, ok_with, raise_with, output_units=None, results=results)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/test_umath.py", line 85, in _test1
    self.assertQuantityAlmostEqual(qm, res, rtol=rtol, msg=err_msg)
  File "/build/1st/python-pint-0.8.1/.pybuild/pythonX.Y_2.7/build/pint/testsuite/__init__.py", line 117, in assertQuantityAlmostEqual
    np.testing.assert_allclose(m1, m2, rtol=rtol, atol=atol, err_msg=msg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=0
At isreal with [ 1.  2.  3.  4.] joule
(mismatch 100.0%)
 x: array(False, dtype=bool)
 y: array([ True,  True,  True,  True], dtype=bool)

----------------------------------------------------------------------
Ran 779 tests in 40.510s
```

**Comment by cpascual** [comment]
Is anyone looking into this?
I am concerned because if this is not fixed, pint may be dropped from debian (and our own package, taurus, would be  dropped as well because it depends on pint)

**Comment by jetheurer** [comment]
Hey @cpascual, I've noticed this error appears in both numpy==1.13.0 and numpy==1.13.1 on Python 2.7 and I believe it is due to the lack of a `__array_ufunc__` method on the `_Quantity` class.  I'm going to look into making a fix along these lines.  

@hgrecco Did you have any thoughts for this ticket?

**Comment by dalito** [comment]
Automated testing on Travis seems to be limited to numpy <= 1.11. So these failures are maybe not too surprising. Testing should extended to include 1.13.x and 1.14.

Numpy 1.13 included improvements to help other projects with subclassing ndarray. Maybe the numpy support in pint can be improved now when using newer numpy versions.

**Comment by cpascual** [comment]
Hi @jetheurer , any progress? 
The deadline for debian packages to be included in Ubuntu LTS 18.04 is 1st of March. I am not sure if https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876921 precludes pint (and the packages depending on it) to be part of the next Ubuntu LTS...

**Comment by jetheurer** [comment]
Hey @cpascual, I don't have anything yet, but I'll try to get something up by Saturday.  Thanks for the 1st March info, that deadline is pretty close!

**Comment by cpascual** [comment]
Hi @jetheurer , do not worry: a debian dev told me that https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876921  does *not* mean that pint will be dropped from Ubuntu

**Comment by bonderado** [comment]
For your information, pint just dropped off Debian Buster: 
check https://tracker.debian.org/pkg/python-pint

**Comment by bonderado** [comment]
For reference: pint just dropped off Debian Buster (https://tracker.debian.org/pkg/python-pint)

**Comment by ChristophBerg** [comment]
All packages depending on pint have been removed from Debian Buster/testing last week. A fix would be very welcome.

**Comment by cpascual** [comment]
I am going to give this a try myself. 
@jetheurer did you get something done?

**Comment by jetheurer** [comment]
@cpascual, go for it.  I dont have anything to show at the moment.

**Comment by cmft** [comment]
Hi @jetheurer, @cpascual ,
I have a look on that, and the problems seem to be in:
- `assertQuantityAlmostEqual` method (in testsuite.__init__.py)
The problem is in `np.testing.assert_allclose(m1, m2, rtol=rtol, atol=atol, err_msg=msg)` 
The `np.testing.assert_allclose` seems to be changed. At naked eye the values seems to be equals.

- `self._magnitude **= _to_magnitude(other, self.force_ndarray)` ( in pint/quantity.py)
If you replace this call for this code the problem is solved.
```
self._magnitude = np.power(self._magnitude,                                                                                                                   
                                             _to_magnitude(other,                                                                                                                       
                                             self.force_ndarray)) 
```

**Comment by jetheurer** [comment]
@cmft That looks like a pretty quick fix.  For some reason I thought the issue was more complicated than that - but maybe it wasn't too bad after all!

**Comment by cpascual** [comment]
Hi @coreycb , yes, I am working on the patch. The problem is that I am not sure on how to approach it. For the moment I am focusing on the tests that give Error (the ones that test Quantity.__ipow__). I am also in touch with @cmft (we are co-workers) and we are trying to understand the ultimate cause of the failures with new numpy versions.

**Comment by cpascual** [comment]
update: I managed to fix the ipow errors and the test_isfinite fail. Now I am working on the test_isreal. Once I get it I'll make the PR

**Comment by cpascual** [comment]
Update: I finally created the PR. Anyone interested, please have a look at it in #630

**Comment by ChristophBerg** [comment]
Thanks for the fix! Could we have a new release with it, or should we rather cherry-pick it for the Debian package?

**Comment by cpascual** [comment]
>Could we have a new release with it, 

About this, I cannot say... maybe @hgrecco can say something.

>or should we rather cherry-pick it for the Debian package?

I just tested cherry picking the following 4 commits on top of the 0.8.1 tag : the tests work fine.
- 71718ea
- 6089601
- bf33e991
- c4d5388

**Comment by cpascual** [comment]
> but I could release 0.8.2 if everyone agrees.

That would be nice, and it would simplify packaging in debian...

**Comment by onovy** [comment]
hi, fyi: I already uploaded cherry-picked version of this fix to Debian this morning.

**Comment by hgrecco** [comment]
I have just updated CHANGES. Please notice that we will be releasing a 0.8.2 in which we have dropped support for Python 2.6, 3.0, 3.1 and 3.2
