### ISSUE TITLE
Allow user to set precision on Dimensions

### ISSUE THREAD

**Issue by peer23peer** [hgrecco/pint#588]
The code below raises an DimensionalityError, due to floating point precision.  Could it be possible to set the precision for Dimensions. 

Such that a `<UnitsContainer({'[length]': 2.9999999999999996, '[mass]': -1.0})>` is stored as `<UnitsContainer({'[length]': 3.0, '[mass]': -1.0})>`

```py
from pint import UnitRegistry

u = UnitRegistry()

m = 1. * u.m ** 3 / u.kg
k = 1.4
s = (m ** k) ** (1 / k)
print(s.dimensionality)
print(m.dimensionality)
s.ito(u.m ** 3 / u.kg)
```

```console

```[length] ** 3 / [mass]
Traceback (most recent call last):
[length] ** 3 / [mass]
  File "D:/Projects/han/TDY2_gasturbine/bug.py", line 10, in <module>
    s.ito(u.m ** 3 / u.kg)
  File "D:\virtualenv\TDY2_gasturbine\lib\site-packages\pint\quantity.py", line 319, in ito
    **ctx_kwargs)
  File "D:\virtualenv\TDY2_gasturbine\lib\site-packages\pint\quantity.py", line 308, in _convert_magnitude
    inplace=isinstance(self._magnitude, ndarray))
  File "D:\virtualenv\TDY2_gasturbine\lib\site-packages\pint\registry.py", line 686, in convert
    return self._convert(value, src, dst, inplace)
  File "D:\virtualenv\TDY2_gasturbine\lib\site-packages\pint\registry.py", line 1214, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "D:\virtualenv\TDY2_gasturbine\lib\site-packages\pint\registry.py", line 937, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
  File "D:\virtualenv\TDY2_gasturbine\lib\site-packages\pint\registry.py", line 708, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'meter ** 3 / kilogram' ([length] ** 3 / [mass]) to 'meter ** 3 / kilogram' ([length] ** 3 / [mass])

**Comment by peer23peer** [comment]
I took the liberty to add a round function to the UnitsContainer.  Which solved my current problem at the moment. 

https://github.com/peer23peer/pint/commit/e2b5a1d15281de6917cb70a82394d0a73ac53c2f

**Comment by peer23peer** [comment]
I took the liberty to add a round function to the UnitsContainer. Which solved my current problem at the moment.
https://github.com/peer23peer/pint/commit/80bfcd4c98ec328384d28cd8bd457488c240ee9f
