### ISSUE TITLE
how to make context work for added units

### ISSUE THREAD

**Issue by AnnisG** [hgrecco/pint#615]
I have a problem getting contexts to work for added units. I checked the documentation for information and also the open issues. I found https://github.com/hgrecco/pint/pull/579 which looked like it could relate to my problem but using the code from enrico's fork I got the same error. Am I doing something wrong (in which case I apologize for bugging you), or is there a bug? 

I have the following unit description file (a test case that fails, not my actual file)

```
# mylength
mymeter = [mylength] = mym
mycm = mymeter / 100 = mycm
mymm = mycm / 10 = mymm

@context test
    [mylength] -> [length]: value * 55
@end
```
I run the following code to load pint and the unit definitions (in an ipython shell)

```
In [1]: import pint

In [2]: ureg = pint.UnitRegistry()

In [3]: ureg.load_definitions('pint_unit_descr_primap.txt')
```
I create a quantity using mymeter

```
In [4]: Q_ = ureg.Quantity

In [5]: testquantity = Q_('25 mymeter')
```
It converts fine to mycm

```

In [7]: testquantity.to('mycm')
Out[7]: 2500.0 mycm
```
But conversion to meter doesn't work

```
In [8]: testquantity.to('cm', 'test')
Traceback (most recent call last):

  File "<ipython-input-9-f92fbda42b40>", line 1, in <module>
    testquantity.to('cm', 'test')

  File "pint/quantity.py", line 339, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)

  File "pint/quantity.py", line 305, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)

  File "pint/registry.py", line 687, in convert
    return self._convert(value, src, dst, inplace)

  File "pint/registry.py", line 1217, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)

  File "pint/registry.py", line 938, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)

  File "pint/registry.py", line 709, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)

DimensionalityError: Cannot convert from 'mymeter' ([mylength]) to 'centimeter' ([length])
```

**Comment by hgrecco** [comment]
You need to define the other equation. See for example:

```
@context boltzmann
    [temperature] -> [energy]: boltzmann_constant * value
    [energy] -> [temperature]: value / boltzmann_constant
@end
```

**Comment by AnnisG** [comment]
Thanks for pointing out that the mistake. Unfortunately fixing that doesn't suffice. It still gives my a dimensionality error. The completed context is:

```
@context test
    [mylength] -> [length]: value * 55
    [length] -> [mylength]: value / 55
@end
```

The same happens when I create a context during runtime
```
c = pint.Context('ab')
c.add_transformation('[length]', '[mylength]',
                     lambda ureg, x: 55 / x)
c.add_transformation('[mylength]', '[length]',
                     lambda ureg, x: 55 * x)
ureg.add_context(c)
Q_ = ureg.Quantity
testquantity = Q_('25 mymeter')
testquantity.to('m','ab')
```
gives

```
---------------------------------------------------------------------------
DimensionalityError                       Traceback (most recent call last)
<ipython-input-61-50187cbb12fe> in <module>()
      7 Q_ = ureg.Quantity
      8 testquantity = Q_('25 mymeter')
----> 9 testquantity.to('m','ab')

pint/quantity.py in to(self, other, *contexts, **ctx_kwargs)
    337         other = to_units_container(other, self._REGISTRY)
    338 
--> 339         magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
    340 
    341         return self.__class__(magnitude, other)

pint/quantity.py in _convert_magnitude_not_inplace(self, other, *contexts, **ctx_kwargs)
    303         if contexts:
    304             with self._REGISTRY.context(*contexts, **ctx_kwargs):
--> 305                 return self._REGISTRY.convert(self._magnitude, self._units, other)
    306 
    307         return self._REGISTRY.convert(self._magnitude, self._units, other)

pint/registry.py in convert(self, value, src, dst, inplace)
    709             return value
    710 
--> 711         return self._convert(value, src, dst, inplace)
    712 
    713     def _convert(self, value, src, dst, inplace=False, check_dimensionality=True):

pint/registry.py in _convert(self, value, src, dst, inplace)
   1240                 value, src = src._magnitude, src._units
   1241 
-> 1242         return super(ContextRegistry, self)._convert(value, src, dst, inplace)
   1243 
   1244     def _get_compatible_units(self, input_units, group_or_system):

pint/registry.py in _convert(self, value, src, dst, inplace)
    993 
    994         if not (src_offset_unit or dst_offset_unit):
--> 995             return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
    996 
    997         src_dim = self._get_dimensionality(src)

pint/registry.py in _convert(self, value, src, dst, inplace, check_dimensionality)
    731             # then the conversion cannot be performed.
    732             if src_dim != dst_dim:
--> 733                 raise DimensionalityError(src, dst, src_dim, dst_dim)
    734 
    735         # Here src and dst have only multiplicative units left. Thus we can

DimensionalityError: Cannot convert from 'mymeter' ([mylength]) to 'meter' ([length])
```

**Comment by vinokurov** [comment]
@AnnisG ,
I had the same issue. I found out that coefficients in the dimensions conversion rules need to have correct units. E.g. in your case 
```
[mylength] -> [length]: value * (55 meter/mymeter)
```

**Comment by AnnisG** [comment]
Thanks a lot, that solved my problem! I'll close the issue now.
