### ISSUE TITLE
Numpy array assigning temperature in different units gives DimensionalityError

### ISSUE THREAD

**Issue by gauravjuvekar** [hgrecco/pint#618]
Python 3.5.2
pint 0.8.1

```
import numpy
import pint

ureg = pint.UnitRegistry()
Q = ureg.Quantity


length = numpy.zeros((4,)) * ureg.meter
temperature = numpy.zeros((4,)) * ureg.kelvin

length[:] = Q(10, 'cm')
temperature[:] = Q(25, 'celsius')
```

```
Traceback (most recent call last):
  File "bug.py", line 12, in <module>
    temperature[:] = Q(25, 'celsius')
  File "/usr/local/lib/python3.5/dist-packages/pint/quantity.py", line 1297, in __setitem__
    factor = self.__class__(value.magnitude, value._units / self._units).to_root_units()
  File "/usr/local/lib/python3.5/dist-packages/pint/quantity.py", line 352, in to_root_units
    magnitude = self._convert_magnitude_not_inplace(other)
  File "/usr/local/lib/python3.5/dist-packages/pint/quantity.py", line 300, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/usr/local/lib/python3.5/dist-packages/pint/registry.py", line 686, in convert
    return self._convert(value, src, dst, inplace)
  File "/usr/local/lib/python3.5/dist-packages/pint/registry.py", line 1214, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "/usr/local/lib/python3.5/dist-packages/pint/registry.py", line 962, in _convert
    extra_msg=' - offset unit used in multiplicative context.')
pint.errors.DimensionalityError: Cannot convert from 'degC / kelvin' to 'dimensionless' - offset unit used in multiplicative context.
```

**Comment by dalito** [comment]
Which version of numpy did you use? Probably you are hitting #577 here.

**Comment by gauravjuvekar** [comment]
Tested in `numpy==1.11.0`, `1.12.0` and `1.14.0`. All three give the same error.

**Comment by hgrecco** [comment]
Same here with python 3.6 and numpy 1.4

if your replace Kelvin by degF you get
```python
Traceback (most recent call last):
  File "t3.py", line 9, in <module>
    temperature = numpy.zeros((4,)) * ureg.degF
  File "/Users/hernan/anaconda3/envs/lantz/lib/python3.6/site-packages/pint/unit.py", line 158, in __mul__
    return self._REGISTRY.Quantity(1, self._units) * other
  File "/Users/hernan/anaconda3/envs/lantz/lib/python3.6/site-packages/pint/quantity.py", line 814, in __mul__
    return self._mul_div(other, operator.mul)
  File "/Users/hernan/anaconda3/envs/lantz/lib/python3.6/site-packages/pint/quantity.py", line 50, in wrapped
    result = f(self, *args, **kwargs)
  File "/Users/hernan/anaconda3/envs/lantz/lib/python3.6/site-packages/pint/quantity.py", line 769, in _mul_div
    getattr(other, 'units', ''))
pint.errors.OffsetUnitCalculusError: Ambiguous operation with offset unit (degF).
```

**Comment by hgrecco** [comment]
You would need to modify `__setitem__` to convert using a safer version.

My suggestion is to use `m_as` to get the magntide of `value` (the rhs) in the units of the `lhs`

**Comment by hgrecco** [comment]
I will be happy to merge a PR
