### ISSUE TITLE
Wraps crashes when using the same unit for different inputvalues

### ISSUE THREAD

**Issue by martinwk** [hgrecco/pint#625]
When I have this function:

```
@ureg.wraps(ureg.M, (ureg.degC, ureg.M, ureg.M))
def hco3_eq_from_tillmans_phreeqc(temperature, CO2, NaCl_conc=__NaCl_conc):
    pass
```
And call it as:

```
temp = ureg.Quantity(12, ureg.degC)
print(mdl.hco3_eq_from_tillmans_phreeqc(temp, 1*ureg.mM, NaCl_conc = 0.1 * ureg.mM))
```
Note how mM=mmol/L, a unit I added to my 

It gives me the following error:

```
Traceback (most recent call last):  File "C:\Users\korevma\.vscode\extensions\ms-python.python-2018.2.1\pythonFiles\PythonTools\visualstudio_py_launcher_nodebug.py", line 74, in run
    _vspu.exec_file(file, globals_obj)
  File "C:\Users\korevma\.vscode\extensions\ms-python.python-2018.2.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 119, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Users\korevma\.vscode\extensions\ms-python.python-2018.2.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 95, in exec_code
    exec(code_obj, global_variables)
```

After removing the third argument, the wrapping works fine. Is it because the same unit is used twice? Does it have something to do with the usage of `unit_args_ndx` in the `_parse_wrap_args` function?

Im am using python 3

**Comment by martinwk** [comment]
O I am sorry... I tested some more and apparently the problem is in the usage of using named_arguments when calling the function and default values in the function definition.
I.e. 

```
print(mdl.hco3_eq_from_tillmans_phreeqc(temp, 1*ureg.mM, NaCl_conc = 0.1 * ureg.mM))
```
does not work and

```
print(mdl.hco3_eq_from_tillmans_phreeqc(temp, 1*ureg.mM,))
```
does not work but 


```
print(mdl.hco3_eq_from_tillmans_phreeqc(temp, 1*ureg.mM, 0.1 * ureg.mM))
```
does work.

So apparently, this is not supported or am I doing it wrong?

**Comment by martinwk** [comment]
Part of my confusion rises because the error message are quite obscure. So probably testing for named keywords on calling the function and raising an appropriate error might be a good idea
