### ISSUE TITLE
Center unit fails to register using UnitRegistry.define

### ISSUE THREAD

**Issue by mcgibbon** [hgrecco/pint#677]
Using Pint 0.7.2. When I define two units in a single command, the center unit doesn't get defined. Is this a bug, or am I incorrectly defining units?

```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> ureg.define('degree_Celsius = degrees_Celsius = degC')
>>> ureg('degrees_Celsius')

Traceback (most recent call last):
  File "/home/twine/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-54-2ad5954d87bf>", line 5, in <module>
    ureg('degrees_Celsius')
  File "/home/twine/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 1271, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x : self._eval_token(x, case_sensitive=case_sensitive,
  File "/home/twine/anaconda3/lib/python3.5/site-packages/pint/pint_eval.py", line 92, in evaluate
    return define_op(self.left)
  File "/home/twine/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 1272, in <lambda>
    **values))
  File "/home/twine/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 1252, in _eval_token
    case_sensitive=case_sensitive) : 1}))
  File "/home/twine/anaconda3/lib/python3.5/site-packages/pint/unit.py", line 753, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'degrees_Celsius' is not defined in the unit registry
```

**Comment by hgrecco** [comment]
Defining multiple aliases works fine, but remember that the second has to be a previously defined unit or a dimension. So the correct command would be:
```python
>>> ureg.define('degree_Celsius = degC = degrees_Celsius')
```

**Comment by mcgibbon** [comment]
Thank you @hgrecco! In retrospect this is fairly clear based on [this documentation](https://github.com/hgrecco/pint/blob/master/docs/defining.rst), I think I was looking at an older PDF earlier which was less clear.
