### ISSUE TITLE
Doc says "no dependencies", but Measurements need external package "uncertainties"

### ISSUE THREAD

**Issue by Tigraan** [hgrecco/pint#734]
The ["Using measurements"](https://pint.readthedocs.io/en/latest/measurement.html) section of the doc does not mention any dependency, and the readme promises
> [pint] runs in Python 2.7 and 3.3+ with no other dependency.

Yet in Python 3.5 (most code taken from the docs) :
```
>>> import pint
>>> pint.__version__
'0.8.1'
>>> import numpy as np
>>> ureg = pint.UnitRegistry()
>>> book_length = (20. * ureg.centimeter).plus_minus(2.)
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    book_length = (20. * ureg.centimeter).plus_minus(2.)
  File "(...)\AppData\Local\Programs\Python\Python35\lib\site-packages\pint\quantity.py", line 1467, in plus_minus
    return self._REGISTRY.Measurement(copy.copy(self.magnitude), error, self._units)
  File "(...)\AppData\Local\Programs\Python\Python35\lib\site-packages\pint\measurement.py", line 136, in __init__
    raise RuntimeError("Pint requires the 'uncertainties' package to create a Measurement object.")
RuntimeError: Pint requires the 'uncertainties' package to create a Measurement object.
```
Shouldn't the dependency be mentioned at least in the relevant section?

**Comment by jules-ch** [comment]
Closing, pint handles dependencies with extras.
Docs specifies Measuremnt needs uncertainties package installed.

Same goes for numpy
