### ISSUE TITLE
reducing of units fails

### ISSUE THREAD

**Issue by dalito** [hgrecco/pint#771]
Based on the example in #770. "to_compact" or "to_baseunits" can convert the quantity but "to_reduced_units" or using the unit registry with `auto_reduce_dimensions = True` fail.

```
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> a = 83.9 * ureg.kilometer**0.5
>>> b = 1. * ureg.meter**0.5/ureg.second
>>> c = a*b
>>> c
<Quantity(83.9, 'kilometer ** 0.5 * meter ** 0.5 / second')>
>>> c.to_compact()
<Quantity(2.65315095688, 'kilometer / second')>
>>> c.to_reduced_units()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\quantity.py", line 452, in to_reduced_units
    newq.ito_reduced_units()
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\quantity.py", line 443, in ito_reduced_units
    return self.ito(newunits)
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\quantity.py", line 362, in ito
    **ctx_kwargs)
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\quantity.py", line 351, in _convert_magnitude
    inplace=isinstance(self._magnitude, ndarray))
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\registry.py", line 711, in convert
    return self._convert(value, src, dst, inplace)
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\registry.py", line 1242, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\registry.py", line 995, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
  File "C:\dev_src\_pyve\stable_py27\lib\site-packages\pint\registry.py", line 733, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'kilometer ** 0.5 * meter ** 0.5 / second' ([length] / [time]) to '1 / second' (1 / [time])
>>> pint.__version__
'0.9'
```

**Comment by dalito** [comment]
Ok. This is not a bug. The doc-string for `to_reduce` tells that it "will not reduce compound units (intentionally)". This was surprising for me because we have suggested more than once that people may use "auto_reduce_dimensions = True" to simplify automatically.

**Comment by bloer** [comment]
FYI, the comment regarding not reducing compound units is not referring to compound statements, but units whose dimensionality contains more than one value.  E.g. a Joule is a `kg*m**2/s**2`, but the function is designed so that `ureg('J/kg').to_reduced_units()` will NOT be converted to  `m**2/s**2`

**Comment by AndySchroder** [comment]
I am confused by this behaviour.

```
In [1]: from pint import UnitRegistry

In [2]: u=UnitRegistry()

In [3]: a=1*u.inch*u.meter

In [4]: a
Out[4]: 1.0 inch·meter

In [5]: a.to_reduced_units()
Out[5]: 0.0254 meter²

In [6]: b=1*u.liter/u.meter

In [7]: b
Out[7]: 1.0 liter/meter

In [8]: b.to_reduced_units()
Out[8]: 0.001 meter²

In [9]: c=1*u.kilometer*u.meter

In [10]: c
Out[10]: 1.0 kilometer·meter

In [11]: c.to_reduced_units()
---------------------------------------------------------------------------
DimensionalityError                       Traceback (most recent call last)
<ipython-input-11-cb0e76a2c225> in <module>()
----> 1 c.to_reduced_units()

/usr/local/lib/python2.7/dist-packages/pint/quantity.pyc in to_reduced_units(self)
    450         #can we make this more efficient?
    451         newq = copy.copy(self)
--> 452         newq.ito_reduced_units()
    453         return newq
    454 

/usr/local/lib/python2.7/dist-packages/pint/quantity.pyc in ito_reduced_units(self)
    441                         break
    442 
--> 443         return self.ito(newunits)
    444 
    445     def to_reduced_units(self):

/usr/local/lib/python2.7/dist-packages/pint/quantity.pyc in ito(self, other, *contexts, **ctx_kwargs)
    360 
    361         self._magnitude = self._convert_magnitude(other, *contexts,
--> 362                                                   **ctx_kwargs)
    363         self._units = other
    364 

/usr/local/lib/python2.7/dist-packages/pint/quantity.pyc in _convert_magnitude(self, other, *contexts, **ctx_kwargs)
    349 
    350         return self._REGISTRY.convert(self._magnitude, self._units, other,
--> 351                                       inplace=isinstance(self._magnitude, ndarray))
    352 
    353     def ito(self, other=None, *contexts, **ctx_kwargs):

/usr/local/lib/python2.7/dist-packages/pint/registry.pyc in convert(self, value, src, dst, inplace)
    709             return value
    710 
--> 711         return self._convert(value, src, dst, inplace)
    712 
    713     def _convert(self, value, src, dst, inplace=False, check_dimensionality=True):

/usr/local/lib/python2.7/dist-packages/pint/registry.pyc in _convert(self, value, src, dst, inplace)
   1240                 value, src = src._magnitude, src._units
   1241 
-> 1242         return super(ContextRegistry, self)._convert(value, src, dst, inplace)
   1243 
   1244     def _get_compatible_units(self, input_units, group_or_system):

/usr/local/lib/python2.7/dist-packages/pint/registry.pyc in _convert(self, value, src, dst, inplace)
    993 
    994         if not (src_offset_unit or dst_offset_unit):
--> 995             return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
    996 
    997         src_dim = self._get_dimensionality(src)

/usr/local/lib/python2.7/dist-packages/pint/registry.pyc in _convert(self, value, src, dst, inplace, check_dimensionality)
    731             # then the conversion cannot be performed.
    732             if src_dim != dst_dim:
--> 733                 raise DimensionalityError(src, dst, src_dim, dst_dim)
    734 
    735         # Here src and dst have only multiplicative units left. Thus we can

DimensionalityError: Cannot convert from 'kilometer * meter' ([length] ** 2) to 'dimensionless' (dimensionless)

```

Why can kilometer and meter not be combined but inch and meter can and liter and 1/meter can?
