### ISSUE TITLE
Bug in Quantity.ito_reduced_units() and algorithm change recommendation

### ISSUE THREAD

**Issue by iankharris** [hgrecco/pint#774]
This is the code of `Quantity.ito_reduced_units` is as follows:

`
    def ito_reduced_units(self):
        """Return Quantity scaled in place to reduced units, i.e. one unit per
        dimension. This will not reduce compound units (intentionally), nor
        can it make use of contexts at this time.
        """
        #shortcuts in case we're dimensionless or only a single unit
        if self.dimensionless:
            return self.ito({})
        if len(self._units) == 1:
            return None

        newunits = self._units.copy()
        #loop through individual units and compare to each other unit
        #can we do better than a nested loop here?
        for unit1, exp in self._units.items():
            for unit2 in newunits:
                if unit1 != unit2:
                    power = self._REGISTRY._get_dimensionality_ratio(unit1,
                                                                     unit2)
                    if power:
                        newunits = newunits.add(unit2, exp/power).remove(unit1)
                        break

        return self.ito(newunits)
`

This code contains a bug which causes it to fail if there are three or more units with the same dimension, because after a unit has been combined in the call to `newunits.add`, the original `self._units` dictionary has not been updated, so if a compatible unit to the  is encountered a second time, the call to `self._REGISTRY._get_dimensionality_ratio` looks at the exponent in the original `self._units` dictionary, NOT the updated exponent after combining.

For instance:

`>>> ureg.Quantity(1, 'ft * yard * inch').to_reduced_units()

Traceback (most recent call last):
  Python Shell, prompt 15, line 1
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/quantity.py", line 452, in to_reduced_units
    newq.ito_reduced_units()
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/quantity.py", line 443, in ito_reduced_units
    return self.ito(newunits)
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/quantity.py", line 362, in ito
    **ctx_kwargs)
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/quantity.py", line 351, in _convert_magnitude
    inplace=isinstance(self._magnitude, ndarray))
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/registry.py", line 711, in convert
    return self._convert(value, src, dst, inplace)
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/registry.py", line 1242, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "/home/syncad/anaconda2/envs/solvercad/lib/python2.7/site-packages/pint/registry.py", line 995, in _convert`

Now, I'm aware that `Quantity.ito_reduced_units` isn't supposed to work for "compound units."  My understanding is that this means units that are composed of more than one dimensional unit.  Frankly, I don't understand what exactly is meant by this, because e.g. Quantity(1, 'lb * ft ** 2 * g') reduces just fine with the existing code -- which is why I'm claiming the above behavior is a bug.  Nonetheless, I'd like to suggest the following revision to "fix the bug" or just "offer an improvement," however you'd like to take it:

`
    def ito_reduced_units(self):
        """Return Quantity scaled in place to reduced units, i.e. one unit per
        dimension. This will not reduce compound units (intentionally), nor
        can it make use of contexts at this time.
        """
        #shortcuts in case we're dimensionless or only a single unit
        if self.dimensionless:
            return self.ito({})
        if len(self._units) == 1:
            return None

        newunits = UnitsContainer()        
        #loop through individual units and compare to each other unit
        #can we do better than a nested loop here?
        for unit1, exp1 in self._units.items():
            for unit2, exp2 in newunits.items():
                power = self._REGISTRY._get_dimensionality_ratio(unit1, unit2)                
                if power:
                    exp1 += exp2 / power
                    newunits = newunits.remove(unit2)
                    break
            if exp1: # UnitsContainer throws exception on adding unit with 0.0 exponent
                newunits = newunits.add(unit1, exp1)

        return self.ito(newunits)
`

This seems to work with the case documented above, as well as passes test_quantity.py (which checks the dimensionality reduction stuff).  More tests would need to be added to test_quantity to ensure this works as expected -- I'm prepared to write those tests, and I apologize because I haven't contributed much to open source projects and I'm unfamiliar with the process.

**Comment by iankharris** [comment]
Forgive me -- it appears that all that's needed to fix this is to remove the "break" statement.  It does make the algorithm a little more costly but it allows for three or more units with compatible dimensionality (so this is the same as the existing code, with the "break" statement commented out):

```
    def ito_reduced_units(self):
        """Return Quantity scaled in place to reduced units, i.e. one unit per
        dimension. This will not reduce compound units (intentionally), nor
        can it make use of contexts at this time.
        """
        #shortcuts in case we're dimensionless or only a single unit
        if self.dimensionless:
            return self.ito({})
        if len(self._units) == 1:
            return None

        newunits = self._units.copy()
        #loop through individual units and compare to each other unit
        #can we do better than a nested loop here?
        for unit1, exp in self._units.items():
            for unit2 in newunits:
                if unit1 != unit2:
                    power = self._REGISTRY._get_dimensionality_ratio(unit1,
                                                                     unit2)
                    if power:
                        newunits = newunits.add(unit2, exp/power).remove(unit1)
                        # break

        return self.ito(newunits)
```

**Comment by bloer** [comment]
FYI, the comment regarding not reducing compound units is not referring to compound statements, but units whose dimensionality contains more than one value.  E.g. a Joule is a `kg*m**2/s**2`, but the function is designed so that `ureg('J/kg').to_reduced_units()` will NOT be converted to  `m**2/s**2`
