### ISSUE TITLE
Comparing Quantity to list yields unhandled IndexError: list index out of range

### ISSUE THREAD

**Issue by alexbhandari** [hgrecco/pint#783]
To replicate run

```
import pint
ureg = pint.UnitRegistry()
ureg('g') == []
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexbhandari-young/miniconda3/envs/django/lib/python3.7/site-packages/pint/quantity.py", line 73, in wrapped
    elif isinstance(other, list) and isinstance(other[0], type(self)):
IndexError: list index out of range

```

This is the case for comparing any Quantity with a list. Seems to be caused by the other[0] access in the check_implemented method used by Quantity.

**Comment by alexbhandari** [comment]
I believe this is fixed by adding 

`elif isinstance(other, list) and other and isinstance(other[0], type(self)):`

on line 73 in quantity.py

**Comment by fedelaport** [comment]
I have similar problems here. I use extensively empty lists:

`[] * ureg.mm` 

and now throws:

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/braced-alB5xfao/lib/python3.6/site-packages/pint/unit.py", line 152, in __mul__
    return self._REGISTRY.Quantity(1, self._units) * other
  File "/root/.local/share/virtualenvs/braced-alB5xfao/lib/python3.6/site-packages/pint/quantity.py", line 900, in __mul__
    return self._mul_div(other, operator.mul)
  File "/root/.local/share/virtualenvs/braced-alB5xfao/lib/python3.6/site-packages/pint/quantity.py", line 73, in wrapped
    elif isinstance(other, list) and isinstance(other[0], type(self)):
IndexError: list index out of range
```

**Comment by hgrecco** [comment]
I have just merge a PR. Let me know if this works

**Comment by fedelaport** [comment]
Works for me. Thank you.
