### ISSUE TITLE
Feature request: relaxing 'Unit expression cannot have a scaling factor.'

### ISSUE THREAD

**Issue by cpitclaudel** [hgrecco/pint#793]
Hi there,

Some measurements in blood tests are customarily expressed in units that include scaling factors; for example,  glomerular filtration rates are typically reported in `mL / min / (1.73 m ** 2)`.  Similarly, hemoglobin levels are typically reported in `g / (100 mL)`.

Pint can parse both of these, but it cannot use them for printing, AFAICT.  For the latter one can use an equivalent unit (`g / dL` instead of `g / (100 mL)`), but is there a good way to handle the former? The only one I know is to define a new alias unit for `1.73 m ** 2` (like `dL` for `100 mL`), but that won't look quite the same.

Here is the concrete issue:

```
>>> ureg = pint.UnitRegistry()
>>> (2 * ureg("60 mL / g / (1.73 m ** 2)")).to('mL / g / (1.73 m ** 2)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/clement/.local/lib/python3.6/site-packages/pint/quantity.py", line 373, in to
    other = to_units_container(other, self._REGISTRY)
  File "/home/clement/.local/lib/python3.6/site-packages/pint/util.py", line 667, in to_units_container
    return registry._parse_units(unit_like)
  File "/home/clement/.local/lib/python3.6/site-packages/pint/registry.py", line 902, in _parse_units
    return super(NonMultiplicativeRegistry, self)._parse_units(input_string, as_delta)
  File "/home/clement/.local/lib/python3.6/site-packages/pint/registry.py", line 812, in _parse_units
    raise ValueError('Unit expression cannot have a scaling factor.')
ValueError: Unit expression cannot have a scaling factor.
```

**Comment by hgrecco** [comment]
This is difficult because of the way parsing works. In other similar issues, people have opted for writing something like `100_mL` or similar.

**Comment by cpitclaudel** [comment]
Oh, of parsing? But these units parse fine; it's just when I try to convert to the units that things break. Am I missing something?

**Comment by hgrecco** [comment]
I meant is a parsing problem because, `100 mL` will always be parsed as a number and a unit.  Allowing this to be a unit will break pint as it will not be clear what is the user intentions.

**Comment by cpitclaudel** [comment]
Thanks! It makes sense now. But maybe it's OK to always assume numbers, unless the user specifies so (using e.g. `Unit`, or the second argument of `Quantity`.  So this wouldn't change:

```
>>> ureg('3.46 mL / min / (1.73 m ** 2)')
<Quantity(2.0, 'milliliter / meter ** 2 / minute')>
```

But this would become allowed:

```
>>> ureg.Quantity(3.46,  'mL / min / (1.73 m ** 2)')
<Quantity(3.46,  'mL / min / (1.73 m ** 2)')>
>>> ureg('3.46 mL / min / (1.73 m ** 2)').to('mL / min / (1.73 m ** 2)')
<Quantity(3.46,  'mL / min / (1.73 m ** 2)')>
```

**Comment by hgrecco** [comment]
I think something like this would be hard because the same parser is used for both units and quantities. But I am open to ideas!

**Comment by kroenlein** [comment]
_n.b._  The solution below is a grotesque hack.  It'd be nice if there was just an initializing argument to UnitRegistry to accept scaling factors (or the constructor switch suggested above).  But it's nastier than most might think, since users think `g / 100 mL` should be `g / (100 mL)`, not `g * mL / 100` as PEDMAS would suggest.

For posterity, if you have a fixed set of numbers you wish to pretend are units, you can add them to your definitions and then add a preprocessor to map the number into the defined object:

```
from pint import UnitRegistry
import re                                                                                                                    

steps = []
def _scaling_preprocessor(input_string: str) -> str:
    for regex, internal in steps:
        input_string = re.sub(regex, internal, input_string)

    return input_string

registry = UnitRegistry(preprocessors=[_scaling_preprocessor])
numbers = [("100", "mL"), ("1.73", "m", "**", "2")]
for number in numbers:
    display = " ".join(number)
    internal = "_" + "_".join(number).replace(".", "_")
    regex = "\s*".join(map(re.escape, number))
    registry.define(f"{display} = {display} = {display} = {internal}")
    steps.append((regex, internal))
```

Exercise for the reader to make the longform output prettier.

**Comment by kroenlein** [comment]
Just discovered ^^ no longer works as for 0.20 -- it now requires that the full name of your units (the bit on the left) must conform to python identifier rules.  The abbreviated component still works.
