### ISSUE TITLE
use_decimal produces floats

### ISSUE THREAD

**Issue by cpitclaudel** [hgrecco/pint#794]
Here's a repro:

```
>>> ureg = UnitRegistry()
>>>  type(ureg('1.0 m / s', use_decimal=True).magnitude)
<class 'decimal.Decimal'>
>>>  type(ureg('1 m / s', use_decimal=True).magnitude)
<class 'float'>
```

This causes the following error (see #788):

```
>>> ureg('1 m / s / (1.5 s)', use_decimal=True)
*** TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
```

cc @franciscouzo

**Comment by franciscouzo** [comment]
A possible fix is to always convert to `Decimal` when `use_decimal` is `True`, currently, the conversion is only done when the token cannot be represented as an `int`

https://github.com/hgrecco/pint/blob/7b9f1ba3683c4ff0156088e4541db753cf3ea1d5/pint/util.py#L429-L435

**Comment by cpitclaudel** [comment]
Indeed, I saw that snippet.  I wonder why the code was written like this?

**Comment by cpitclaudel** [comment]
I think this might be the only reasonable trick; if we don't do that, then there's no difference between `ureg('1')` and `ureg('1', use_decimal=True)`, which means that then the `*` and `/` operator can't know which unit to use.

**Comment by cpitclaudel** [comment]
Ah, this solution doesn't work: it breaks exponents.

```
>>> ureg('m ** 2', use_decimal=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pint/pint/registry.py", line 865, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x: self._eval_token(x,
  File ".../pint/pint/pint_eval.py", line 85, in evaluate
    return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
  File ".../pint/pint/quantity.py", line 76, in wrapped
    result = f(self, *args, **kwargs)
  File ".../pint/pint/quantity.py", line 1164, in __pow__
    units = new_self._units ** other
  File ".../pint/pint/util.py", line 366, in __pow__
    d[key] *= other
TypeError: unsupported operand type(s) for *=: 'float' and 'decimal.Decimal'
```

**Comment by cpitclaudel** [comment]
Constructing a container doesn't work either:

```
>>> ureg.Unit(pint.util.UnitsContainer({'m': Decimal(1.3)})) ** Decimal(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/clement/documents/projects/blood-chemistry/pint/pint/unit.py", line 181, in __pow__
    return self.__class__(self._units**other)
  File "/home/clement/documents/projects/blood-chemistry/pint/pint/util.py", line 366, in __pow__
    d[key] *= other
TypeError: unsupported operand type(s) for *=: 'float' and 'decimal.Decimal'
```

… that's because unit exponents are are cast to float:

https://github.com/hgrecco/pint/blob/7b9f1ba3683c4ff0156088e4541db753cf3ea1d5/pint/util.py#L257-L267

**Comment by hgrecco** [comment]
An option will be to use Decimal **everywhere** when `use_decimal` is chosen. This will help also fix other bugs apearing when rounding exponents.

**Comment by cpitclaudel** [comment]
I think that's a great idea; and, if we take the trouble to do this, then generalizing to any numeric constructor would probably be better.

**Comment by hgrecco** [comment]
I agree.

**Comment by ickedude** [comment]
From docs:
```python
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry('/your/path/to/default_es.txt')
```
How do I define that a definition file is parsed with use_decimal?

In my opinion the numeric type must be chosen on instantiation of the registry. Like units of different unit registries are incompatible, it should be with different numeric systems. If you define at registry level which numeric system to use explicitly, then everyone knows that an implicit conversation/parsing can happen.

**Comment by ickedude** [comment]
Two other problems I came across:

1. ```udict``` is also returning float by default:
    https://github.com/hgrecco/pint/blob/b5127a2dbbbcde9241aeb717612c8516e7c54186/pint/util.py#L239-L244
2. ```__pow__``` will initialize a ```ParserHelper``` with a float scale if the exponent is negative.
    https://github.com/hgrecco/pint/blob/b5127a2dbbbcde9241aeb717612c8516e7c54186/pint/util.py#L530-L534
    This will result in something like
     ```
    ERROR:pint.util:In line 23, cannot add 'boltzmann_constant = 1.380649e-23 J K^-1 = k = k_B' unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
    ```

**Comment by CD3** [comment]
Has there been any progress on this? I ran into this my error propagation library. You can't take the square root of a quantity that uses `decimal.Decimal`:
```python
...
A = ureg.Quantity('1.5','cm^2')

x = A**0.5
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cclark/virtualenvs/py2/lib/python2.7/site-packages/pint/quantity.py", line 1008, in __pow__
    magnitude = new_self._magnitude ** _to_magnitude(other, self.force_ndarray)
TypeError: unsupported operand type(s) for ** or pow(): 'Decimal' and 'float'
unsupported operand type(s) for ** or pow(): 'Decimal' and 'float'
```
Converting the exponent to `decimal.Decimal` works for decimals, but not Pint quantities:
```
x**decimal.Decimal(0.5)
```
gives
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cclark/virtualenvs/py2/lib/python2.7/site-packages/pint/quantity.py", line 1006, in __pow__
    units = new_self._units ** other
  File "/home/cclark/virtualenvs/py2/lib/python2.7/site-packages/pint/util.py", line 360, in __pow__
    d[key] *= other
TypeError: unsupported operand type(s) for *=: 'float' and 'Decimal'
unsupported operand type(s) for *=: 'float' and 'Decimal'
```
The error is different, so Pint calculates the square root of the value, but then fails to compute the square root of the unit.

**Comment by andrewgsavage** [comment]
```
ureg = pint.UnitRegistry(non_int_type=decimal.Decimal)
type(ureg('1.0 m / s').magnitude)
decimal.Decimal

type(ureg('1 m / s').magnitude)
decimal.Decimal
```

this works now
