### ISSUE TITLE
Feature request: a way to programatically change default abbreviations

### ISSUE THREAD

**Issue by cpitclaudel** [hgrecco/pint#797]
Hi there,

Is there a (programmatic) way to change the `u` prefix to a `µ` in formatted units, and to use `L` consistently instead of `l` for litters when printing?

I can copy and edit default_en, but it's a bit heavy-handed.  Is there a simpler way?

Thanks!

**Comment by hgrecco** [comment]
You can grab de UnitDefinition object, edit it and then rebuild the cache. I think it would be good to create a context manager that builds the cache afterwards. Something like:

```python
with ureg.edit():
     # Do things here
```

**Comment by cpitclaudel** [comment]
Interesting, thanks! I changed the contents of the `_units` dictionary, but it seems I have to change both `l` and `ml`; is there something special about the `m-` prefix?

**Comment by hgrecco** [comment]
In pint, prefixes are stored in the `_prefixes` dictionary in order to be composed with any other unit.

**Comment by cpitclaudel** [comment]
Got it. But is it expected that _units should have entries for `l` and `ml`, but dot e.g. for `kl`, `ul`, etc?

**Comment by hgrecco** [comment]
That is true in theory, but in practice we do add those units for performance reasons when they are first used. For example:
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg._units['decameter']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'decameter'
>>> 10 * ureg('decameter')
<Quantity(10, 'decameter')>
>>> ureg._units['decameter']
<pint.definitions.UnitDefinition object at 0x10c33af98>
```
That is why only reference units are used when rebuilding the cache [here](https://github.com/hgrecco/pint/blob/master/pint/registry.py#L412)

**Comment by cpitclaudel** [comment]
Thanks, that's very useful.  I tried the following, but I think I'm still missing something:

```python
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> ureg._units['liter']
<pint.definitions.UnitDefinition object at 0x7f5f3ac25940>
>>> ureg._units['milliliter']
<pint.definitions.UnitDefinition object at 0x7f5f3abd94a8>
>>> ureg._units['liter']._symbol
'l'
>>> ureg._units['milliliter']._symbol
'ml'
>>> ureg._units['liter']._symbol = 'L'
>>> ureg._build_cache()
>>> ureg._units['liter']._symbol
'L'
>>> ureg._units['milliliter']._symbol
'ml'
```

**Comment by hgrecco** [comment]
This needs to be fixed. Briefly, the problem is that the only the cache is being recalculated not the definition list. If you manually delete the unit, then it works:
```python
>>> del ureg._units['milliliter']
>>> ureg._units['milliliter']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'milliliter'
>>> ureg('milliliter')
<Quantity(1, 'milliliter')>
>>> ureg._units['milliliter']._symbol
'mL'
```
This new use case will require some reorganization of the code.

**Comment by cpitclaudel** [comment]
Thanks a lot for the clarification
