### ISSUE TITLE
'NotImplementedType' object has no attribute '_REGISTRY' [Units]

### ISSUE THREAD

**Issue by am-thyst** [hgrecco/pint#832]
Using MetPy to calculate some quantities. I get the following error, associated with the pint.units. Never had this before. Any suggestions?

```python
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/242075.rdf-xcat.SC", line 92, in <module>
    pool.map(cape_func, range(0,1))
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 761, in map
    raise pg.get_exception()
sharedmem.sharedmem.SlaveException: 'NotImplementedType' object has no attribute '_REGISTRY'
Traceback (most recent call last):
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 294, in _slaveMain
    self.main(self, *self.args)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 628, in _main
    r = realfunc(work)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 703, in realfunc
    else: return func(i)
  File "/var/spool/torque/mom_priv/jobs/242075.rdf-xcat.SC", line 87, in cape_func
    cape, cin = surface_based_cape_cin((vl_lst * units.hPa) (prof_t * units.kelvin), (prof_td * units.kelvin))
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/pint/unit.py", line 158, in __mul__
    return self._REGISTRY.Quantity(1, self._units) * other
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/pint/quantity.py", line 814, in __mul__
    return self._mul_div(other, operator.mul)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.6/site-packages/pint/quantity.py", line 51, in wrapped
    if result._REGISTRY.auto_reduce_dimensions:
AttributeError: 'NotImplementedType' object has no attribute '_REGISTRY'
```

**Comment by hgrecco** [comment]
You will need to post this in MetPy as it seems to be internal problema,.
