### ISSUE TITLE
TypeError: missing a required argument: 'owner' when wrapping a property with wraps

### ISSUE THREAD

**Issue by bilderbuchi** [hgrecco/pint#847]
I have a class with lots (20+) defined properties, which accept/return unitless/plain numbers. I know the respective units they should use, so I want to wrap the properties programmatically with `wraps` by defining new properties (best way I could identify).

For some reason, I get a mysterious`TypeError: missing a required argument: 'owner'`, but I cannot see why or how to troubleshoot this. Any pointers?

Repro code:
```
import inspect

import pint

ureg = pint.UnitRegistry()

class MyClass():
    @property
    def myprop(self):
        """this should return volt"""
        return 42

    @myprop.setter
    def myprop(self, value):
        """this should accept volt"""
        print('setting myprop')

properties = {k: v for (k, v)
              in inspect.getmembers(MyClass, lambda x: isinstance(x, property))}
print(properties)

for k, v in properties.items():  # Assume we have lots of properties here
    unit = 'V'
    old_property = getattr(MyClass, k)
    new_property = property(ureg.wraps(ret=unit, args=None)(old_property.__get__),
                            ureg.wraps(ret=None, args=unit)(old_property.__set__),
                            old_property.__delattr__,
                            )
    setattr(MyClass, k, new_property)

my_inst = MyClass()
# OK, let's execute, this should return quantities now
print('Getting a property value now:')
print(my_inst.myprop)
```

Running this gives
```
{'myprop': <property object at 0x7f789c23d8b8>}
Getting a property value now:
Traceback (most recent call last):
  File "/home/bilderbuchi/FOTEC/Z_stuff/labcontrol/labcontrol/controller/pint_bug.py", line 34, in <module>
    print(my_inst.myprop)
  File "/home/bilderbuchi/anaconda3/lib/python3.6/site-packages/pint/registry_helpers.py", line 188, in wrapper
    values, kw = _apply_defaults(func, values, kw)
  File "/home/bilderbuchi/anaconda3/lib/python3.6/site-packages/pint/registry_helpers.py", line 141, in _apply_defaults
    bound_arguments = sig.bind(*args, **kwargs)
  File "/home/bilderbuchi/anaconda3/lib/python3.6/inspect.py", line 2997, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/home/bilderbuchi/anaconda3/lib/python3.6/inspect.py", line 2912, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'owner'
```

This is on Python 3.6 with pint 0.9

**Comment by hgrecco** [comment]
Wrapping properties is not that easy. Properties are objects that implement the descriptor protocol and the corresponding methods (__get__, __set__) contain parameters. 

I frequently do this but creating a new type of property that works exactly the same way. There is an example [here](https://github.com/lantzproject/lantz-core/blob/master/lantz/core/feat.py#L54) but it does much more than what you need. Maybe we can design a more convenient solution.

**Comment by bilderbuchi** [comment]
Thanks for the input, I'll try to grok the Lantz code.
I could confirm that wrapping properties at creation works as expected. You have to have an additional `None` in the argslist to account for the `self` in methods, though.
```
class MyClass():
    # You have to account for the self argument with the args=None!
    @property
    @ureg.wraps(ret=ureg.second, args=None)
    def directprop(self):
        """this should return volt"""
        return 42

    @directprop.setter
    @ureg.wraps(ret=None, args=(None, ureg.second))
    def directprop(self, value):
        """this should accept volt"""
        print(f'setting directprop, got passed {value}')
```
Now I "just" have to find a way to do the wrapping after creation. :D

**Comment by hgrecco** [comment]
If I remember correctly the inner workings of `property`, I think you can wrap it after creation if you do
```python
    new_property = property(ureg.wraps(ret=unit, args=None)(old_property.fget),
                            ureg.wraps(ret=None, args=(None, unit))(old_property.fset),
                            old_property.__delattr__,
                            )
```
Notice that `__get__` became `fget` and similarly `__set__` became `fset`, in addition to `None` for self.

**Comment by bilderbuchi** [comment]
Ha, right, that way it works. Thank you!
