### ISSUE TITLE
Sphinx errors

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#881]
Downstream of #880, I'm still getting a few errors when running sphinx-build:

```
pint/docs/plotting.rst:32: WARNING: Exception occurred in plotting plotting-1
 from pint/docs/plotting.rst:
Traceback (most recent call last):
  File "pint/pint/quantity.py", line 1476, in __getitem__
    value = self._magnitude[key]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/matplotlib/sphinxext/plot_directive.py", line 499, in run_code
    exec(code, ns)
  File "<string>", line 13, in <module>
  File "site-packages/matplotlib/axes/_axes.py", line 798, in axhline
    yy = self.convert_yunits(y)
  File "site-packages/matplotlib/artist.py", line 195, in convert_yunits
    return ax.yaxis.convert_units(y)
  File "site-packages/matplotlib/axis.py", line 1521, in convert_units
    if munits.ConversionInterface.is_numlike(x):
  File "site-packages/matplotlib/units.py", line 126, in is_numlike
    for thisx in x:
  File "pint/pint/quantity.py", line 1480, in __getitem__
    "supports indexing".format(self._magnitude))
TypeError: Neither Quantity object nor its magnitude (26400)supports indexing
pint/docs/plotting.rst:52: WARNING: Exception occurred in plotting plotting-2
 from pint/docs/plotting.rst:
Traceback (most recent call last):
  File "pint/pint/quantity.py", line 1476, in __getitem__
    value = self._magnitude[key]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/matplotlib/sphinxext/plot_directive.py", line 499, in run_code
    exec(code, ns)
  File "<string>", line 16, in <module>
  File "site-packages/matplotlib/axes/_axes.py", line 798, in axhline
    yy = self.convert_yunits(y)
  File "site-packages/matplotlib/artist.py", line 195, in convert_yunits
    return ax.yaxis.convert_units(y)
  File "site-packages/matplotlib/axis.py", line 1521, in convert_units
    if munits.ConversionInterface.is_numlike(x):
  File "site-packages/matplotlib/units.py", line 126, in is_numlike
    for thisx in x:
  File "pint/pint/quantity.py", line 1480, in __getitem__
    "supports indexing".format(self._magnitude))
TypeError: Neither Quantity object nor its magnitude (26400)supports indexing

pint/pint/quantity.py:docstring of pint.Quantity:: WARNING: py:class reference target not found: any numeric type                                                                                                                   
pint/pint/quantity.py:docstring of pint.Quantity.from_list:: WARNING: py:class reference target not found: list of pint.Quantity
pint/pint/quantity.py:docstring of pint.Quantity.from_sequence:: WARNING: py:class reference target not found: sequence of pint.Quantity
pint/pint/quantity.py:docstring of pint.quantity.Quantity:: WARNING: py:class reference target not found: any numeric type
pint/pint/quantity.py:docstring of pint.quantity.Quantity.from_list:: WARNING: py:class reference target not found: list of pint.Quantity
pint/pint/quantity.py:docstring of pint.quantity.Quantity.from_sequence:: WARNING: py:class reference target not found: sequence of pint.Quantity
pint/pint/systems.py:docstring of pint.systems.Group.from_lines:: WARNING: py:class reference target not found: str -> None

**Comment by jthielen** [comment]
The `TypeError`s you're receiving look a lot like https://github.com/hgrecco/pint/issues/751 and https://github.com/hgrecco/pint/issues/760, which should be fixed by https://github.com/hgrecco/pint/pull/875 (or the original https://github.com/hgrecco/pint/pull/764). Would you be able to see if that is the case?

**Comment by hgrecco** [comment]
I am not getting this error any more, @crusaderky can you comment?

**Comment by crusaderky** [comment]
Sorry I won't have access to a computer until Jan 2nd

**Comment by crusaderky** [comment]
On readthedocs, something is going horribly wrong - it's still using Python 2.7, which fails to parse any source file:
https://readthedocs.org/projects/pint/builds/10207877/

For the same reason, intersphinx is failing to generate references in objects.inv to pint.UnitRegistry, pint.Quantity, etc.

Locally, I'm getting several pages of errors, including (but not limited to) many " WARNING: Unexpected section title." which should not happen with nbsphinx enabled...

**Comment by hgrecco** [comment]
I have changed read the docs to cpython 3.X. The docs, while not perfect, should be usable for 0.10.
