### ISSUE TITLE
RecursionError when reassigning 'ohm'

### ISSUE THREAD

**Issue by mrclary** [hgrecco/pint#886]
So, for some circumstances I need to change the preference order of unit aliases (the first one is returned by a registry's `get_symbol` method). I have done this by using the registry's `define` method, for example:
```python
>>> from pint import UnitRegistry
>>> u = UnitRegistry()
>>> u.get_symbol('ohm')
'Ω'
>>> u('ohm').to_base_units()
<Quantity(1.0, 'kilogram * meter ** 2 / ampere ** 2 / second ** 3')>
>>> u.define('ohm = Ω')
>>> u.get_symbol('ohm')
'ohm'
>>> u('ohm').to_base_units()
<Quantity(1.0, 'kilogram * meter ** 2 / ampere ** 2 / second ** 3')>
>>> 
```
However, if the first call to `u('ohm').to_base_units()` is omitted, then a `RecursionError` occurs
```python
>>> from pint import UnitRegistry
>>> u = UnitRegistry()
>>> u.get_symbol('ohm')
'Ω'
>>> u.define('ohm = Ω')
>>> u.get_symbol('ohm')
'ohm'
>>> u('ohm').to_base_units()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/quantity.py", line 415, in to_base_units
    magnitude = self._convert_magnitude_not_inplace(other)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/quantity.py", line 343, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 711, in convert
    return self._convert(value, src, dst, inplace)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 1242, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 995, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 737, in _convert
    factor, units = self._get_root_units(src / dst)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 626, in _get_root_units
    self._get_root_units_recurse(input_units, 1.0, accumulators)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 670, in _get_root_units_recurse
    accumulators)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 670, in _get_root_units_recurse
    accumulators)
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 670, in _get_root_units_recurse
    accumulators)
  [Previous line repeated 986 more times]
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/registry.py", line 660, in _get_root_units_recurse
    for key in sorted(ref):
  File "/Users/rclary/anaconda3/envs/c2w_37/lib/python3.7/site-packages/pint/util.py", line 298, in __iter__
    return iter(self._d)
RecursionError: maximum recursion depth exceeded while calling a Python object
>>> 
```
I've tried the same pattern with different units and believe it only seems to afflict 'ohm' but I'm not sure why. The issue does not manifest if I use `u.define('ohm = volt / ampere = ohm = Ω')`, but, again, it does not seem to apply to other units, such as 'pixel' and 'degC'.

Anaconda
Python = 3.7.4
pint = 0.9

**Comment by hgrecco** [comment]
Because the first part after the equal sign is the definition of the unit and must be expressed in terms of previously defined units. See the syntax in the docs and ping back if you need any help.

**Comment by mrclary** [comment]
I figured that perhaps I was cheating on the syntax, but I still think that it's strange that the RecursionError doesn't result for other units, only 'ohm'. Perhaps the real issue here is not that 'ohm' produces the RecursionError but that other units _don't_.
