### ISSUE TITLE
DimensionalityError with auto_reduce_dimensions=True

### ISSUE THREAD

**Issue by pcatach** [hgrecco/pint#902]
I have encountered the following situation: a division between two quantities gives an error depending on the operand's order:
```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry(auto_reduce_dimensions=True)
>>> velocity = 1 *ureg.m/ureg.s
>>> cross_section = 1 * ureg.um**2
>>> velocity / cross_section
<Quantity(1000000.0, '1 / micrometer / second')>
>>> 1 / (velocity / cross_section)
<Quantity(1e-06, 'micrometer * second')>
>>> cross_section/velocity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/quantity.py", line 911, in __truediv__
    return self._mul_div(other, operator.truediv)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/quantity.py", line 75, in wrapped
    result = f(self, *args, **kwargs)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/quantity.py", line 62, in wrapped
    result.ito_reduced_units()
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/quantity.py", line 443, in ito_reduced_units
    return self.ito(newunits)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/quantity.py", line 362, in ito
    **ctx_kwargs)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/quantity.py", line 351, in _convert_magnitude
    inplace=isinstance(self._magnitude, ndarray))
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/registry.py", line 711, in convert
    return self._convert(value, src, dst, inplace)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/registry.py", line 1242, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/registry.py", line 995, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
  File "/home/pcatach/Projects/test/env/lib/python3.7/site-packages/pint/registry.py", line 733, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'micrometer ** 2 * second / meter' ([length] * [time]) to 'second' ([time])
```
The error does not occur when I have `auto_reduce_dimensions` set to `False`. It also does not occur when `cross_section` is set to `1*ureg.m**2` (but it persists if `nm`, `pm`, etc.)
`python=3.7.3`
`pint=0.9`

**Comment by hgrecco** [comment]
Can you run it with `auto_reduce_dimensions=False` and ouput the units of the result?

**Comment by pcatach** [comment]
```>>> from pint import UnitRegistry
>>> ureg = UnitRegistry(auto_reduce_dimensions=False)
>>> velocity = 1 * ureg.m/ureg.s
>>> cross_section = 1 * ureg.um**2
>>> velocity/cross_section
<Quantity(1.0, 'meter / micrometer ** 2 / second')>
>>> 1 / (velocity / cross_section)
<Quantity(1.0, 'micrometer ** 2 * second / meter')>
>>> cross_section/velocity
<Quantity(1.0, 'micrometer ** 2 * second / meter')>
```

Works as expected. The same error is raised using `Quantity.to()`:
```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry(auto_reduce_dimensions=False)
>>> (1 * ureg.micrometer ** 2 * ureg.second / ureg.meter).to("m s")
<Quantity(1e-12, 'meter * second')>
>>> ureg = UnitRegistry(auto_reduce_dimensions=True)
>>> (1 * ureg.micrometer ** 2 * ureg.second / ureg.meter).to("m s")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/quantity.py", line 911, in __truediv__
    return self._mul_div(other, operator.truediv)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/quantity.py", line 75, in wrapped
    result = f(self, *args, **kwargs)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/quantity.py", line 62, in wrapped
    result.ito_reduced_units()
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/quantity.py", line 443, in ito_reduced_units
    return self.ito(newunits)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/quantity.py", line 362, in ito
    **ctx_kwargs)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/quantity.py", line 351, in _convert_magnitude
    inplace=isinstance(self._magnitude, ndarray))
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/registry.py", line 711, in convert
    return self._convert(value, src, dst, inplace)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/registry.py", line 1242, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/registry.py", line 995, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
  File "/home/pcatach/Projects/misc/env/lib/python3.7/site-packages/pint/registry.py", line 733, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'micrometer ** 2 * second / meter' ([length] * [time]) to 'second' ([time])
```

**Comment by jules-ch** [comment]
The error comes from line 520 in `quantity.py` : 
```python
newunits = newunits.add(unit2, exp/power).remove(unit1)
```
This is where the reduction is done.

The remove implementation needs an iterable : 
```python
    def remove(self, keys):
        """ Create a new UnitsContainer purged from given keys.

        """
        new = self.copy()
        for k in keys:
            new._d.pop(k, None)
        new._hash = None
        return new
```

Here `micrometer` is sent which is an iterable but since the pop function is not raising an error for key that don't exists with the None argument, the error is silent.

Changing to
 ````python
newunits = newunits.add(unit2, exp/power).remove([unit1])
````
fixes it.

IMO we should do something about it, since we're moving to Python 3, refactoring some part to be safer like raising an Error here is a good idea.

I'm submitting a PR with the fix.
