### ISSUE TITLE
measurements with numpy: doc and exceptions

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#918]
As of git tip, pint doesn't support measurements and numpy at the same time.
XREF: #128, #350 

Also related: #734

Short of a proper implementation as discussed in the linked documents, there are a few things that bug me:

1. this command:
```python
pint.Quantity([1,2], "m").plus_minus(.5)
```
produces a very dirty Exception:
```
Traceback (most recent call last):
  File "/Users/crusaderky/miniconda3/envs/pint/lib/python3.6/site-packages/uncertainties/core.py", line 3233, in ufloat
    return Variable(nominal_value, std_dev, tag=tag)
  File "/Users/crusaderky/miniconda3/envs/pint/lib/python3.6/site-packages/uncertainties/core.py", line 2719, in __init__
    value = float(value)
TypeError: only size-1 arrays can be converted to Python scalars
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/crusaderky/miniconda3/envs/pint/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-36473b74231e>", line 1, in <module>
    pint.Quantity([1,2], "m").plus_minus(.5)
  File "/Users/crusaderky/PycharmProjects/pint/pint/quantity.py", line 1718, in plus_minus
    return self._REGISTRY.Measurement(copy.copy(self.magnitude), error, self._units)
  File "/Users/crusaderky/PycharmProjects/pint/pint/measurement.py", line 48, in __new__
    mag = ufloat(value, error)
  File "/Users/crusaderky/miniconda3/envs/pint/lib/python3.6/site-packages/uncertainties/core.py", line 3246, in ufloat
    final_ufloat = ufloat_obsolete(nominal_value, tag_arg)
  File "/Users/crusaderky/miniconda3/envs/pint/lib/python3.6/site-packages/uncertainties/core.py", line 3189, in ufloat_obsolete
    return ufloat_fromstr(representation, tag)
  File "/Users/crusaderky/miniconda3/envs/pint/lib/python3.6/site-packages/uncertainties/core.py", line 3173, in ufloat_fromstr
    representation.strip())
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
```

2. <https://pint.readthedocs.io/en/latest/measurement.html> starts with ``import numpy as np``, which is then not used in the document. On the opposite, the document should clearly state that measurements and numpy don't work together.

**Comment by miketynes** [comment]
As of most recent release, using numpy and uncertainties together still is impossible. Is there any development plan to make this possible? This would be a very convenient feature.

**Comment by andrewgsavage** [comment]
[uncertainties-pandas](https://github.com/andrewgsavage/uncertainties-pandas) can be used [with pint-pandas](https://pint-pandas.readthedocs.io/en/latest/user/initializing.html#non-native-pandas-dtypes)
