### ISSUE TITLE
Slug and slinch not recognized in UnitRegistry

### ISSUE THREAD

**Issue by clark3493** [hgrecco/pint#952]
Slug and slinch are not recognized in the UnitRegistry, although they do appear to be defined in default_en.txt.

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> x = 3. * ureg.slug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\clark\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\registry.py", line 203, in __getattr__
    return self.Unit(item)
  File "C:\Users\clark\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\unit.py", line 46, in __new__
    inst._units = inst._REGISTRY.parse_units(units)._units
  File "C:\Users\clark\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\registry.py", line 792, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "C:\Users\clark\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\registry.py", line 902, in _parse_units
    return super(NonMultiplicativeRegistry, self)._parse_units(input_string, as_delta)
  File "C:\Users\clark\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\registry.py", line 817, in _parse_units
    cname = self.get_name(name)
  File "C:\Users\clark\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\registry.py", line 478, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'slug' is not defined in the unit registry
```

**Comment by jthielen** [comment]
Are you using a released version, or the current master branch from GitHub? This have only recently been made available, so I think you will need to be on the current master branch, wait until the next release, or load the `default_en.txt` from the current master branch with your version of pint.

For example, on the current master branch:

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> x = 3. * ureg.slug
>>> x
<Quantity(3.0, 'slug')>
```

**Comment by clark3493** [comment]
Roger that - didn't realize these hadn't been rolled into the latest release available on pip yet. Thanks for the quick reply!
